-- Seed MICA Sample Data
-- Insert sample MICA assessments
INSERT INTO mica_assessments (assessment_name, assessment_type, organization_id, assessor_name, assessment_date, status, scope_description, methodology, overall_score, maturity_level, executive_summary, key_findings, recommendations, next_review_date, created_by) VALUES
('MICA Compliance Assessment 2024', 'External Assessment', 1, 'MICA Compliance Auditor', '2024-01-15', 'Completed', 'Comprehensive assessment of MICA compliance across all business units', 'Risk-based assessment methodology following MICA guidelines', 78.5, 'Managed', 'Organization demonstrates good compliance posture with some areas for improvement', 'Strong governance framework, gaps in technical controls', 'Implement advanced monitoring and enhance incident response', '2024-07-15', 1),
('MICA Self-Assessment Q1 2024', 'Self-Assessment', 1, 'Internal Audit Team', '2024-03-01', 'Completed', 'Quarterly self-assessment of MICA compliance status', 'Internal assessment using MICA self-assessment framework', 82.3, 'Managed', 'Continued improvement in compliance maturity', 'Enhanced data protection measures, improved access controls', 'Focus on supply chain security and vendor management', '2024-06-01', 2),
('MICA Gap Analysis 2024', 'Gap Analysis', 1, 'Risk Management Team', '2024-02-10', 'In Progress', 'Detailed gap analysis against MICA requirements', 'Comprehensive gap assessment methodology', 75.2, 'Defined', 'Systematic identification of compliance gaps', 'Network security gaps, incomplete documentation', 'Prioritize critical gaps and develop remediation roadmap', '2024-05-10', 1);

-- Insert sample MICA assessment results
INSERT INTO mica_assessment_results (assessment_id, requirement_id, compliance_status, implementation_score, evidence_provided, gaps_identified, remediation_plan, target_completion_date, responsible_party, comments, assessor_notes) VALUES
(1, 1, 'Compliant', 90, 'Board-approved information security policy, governance committee charter', 'Minor gaps in policy review frequency', 'Update policy review schedule to quarterly', '2024-06-30', 'CISO', 'Strong governance foundation', 'Well-documented governance structure'),
(1, 2, 'Partially Compliant', 75, 'Risk assessment methodology, risk register', 'Incomplete threat modeling, limited quantitative analysis', 'Implement comprehensive threat modeling and quantitative risk analysis', '2024-08-31', 'Risk Manager', 'Good foundation but needs enhancement', 'Risk management process exists but requires maturity'),
(1, 3, 'Compliant', 85, 'Data classification policy, classification labels', 'Some legacy data not classified', 'Complete classification of legacy data assets', '2024-07-31', 'Data Protection Officer', 'Good classification scheme in place', 'Classification process well-defined'),
(1, 4, 'Partially Compliant', 70, 'Encryption standards, key management procedures', 'Inconsistent encryption implementation', 'Standardize encryption across all systems', '2024-09-30', 'IT Security Manager', 'Encryption standards defined but implementation varies', 'Need consistent encryption deployment'),
(1, 5, 'Compliant', 88, 'IAM system, access control policies', 'Minor issues with access reviews', 'Automate access review processes', '2024-06-15', 'Identity Manager', 'Strong access control framework', 'Well-implemented IAM solution'),
(2, 1, 'Compliant', 92, 'Updated governance documentation', 'None identified', 'Continue regular governance reviews', '2024-09-01', 'CISO', 'Excellent governance maturity', 'Governance framework continuously improving'),
(2, 2, 'Compliant', 85, 'Enhanced risk assessment process', 'Limited automation in risk monitoring', 'Implement automated risk monitoring tools', '2024-10-31', 'Risk Manager', 'Significant improvement in risk management', 'Risk processes showing good maturity'),
(2, 3, 'Compliant', 90, 'Comprehensive data classification', 'None identified', 'Maintain current classification standards', '2024-12-31', 'Data Protection Officer', 'Excellent data classification program', 'Data classification fully implemented'),
(3, 1, 'Compliant', 88, 'Governance framework assessment', 'Documentation gaps', 'Complete governance documentation', '2024-07-31', 'CISO', 'Good governance structure', 'Governance assessment in progress'),
(3, 2, 'Partially Compliant', 72, 'Risk management review', 'Process automation needed', 'Implement risk management automation', '2024-11-30', 'Risk Manager', 'Risk management needs enhancement', 'Gap analysis identifies automation opportunities');

-- Insert sample MICA self-assessments
INSERT INTO mica_self_assessments (assessment_name, organization_id, assessment_period, status, overall_maturity_score, completion_percentage, started_date, completed_date, reviewed_by, approved_by, approval_date, executive_summary, key_strengths, improvement_areas, strategic_recommendations, created_by) VALUES
('MICA Self-Assessment 2024 Q1', 1, '2024 Q1', 'Completed', 83.5, 100, '2024-01-01', '2024-03-31', 'Chief Risk Officer', 'Chief Executive Officer', '2024-04-15', 'Strong compliance posture with continuous improvement focus', 'Robust governance, effective risk management, strong data protection', 'Network security monitoring, incident response automation', 'Invest in advanced security technologies and enhance monitoring capabilities', 1),
('MICA Self-Assessment 2024 Q2', 1, '2024 Q2', 'In Progress', 85.2, 75, '2024-04-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);

-- Insert sample MICA self-assessment controls
INSERT INTO mica_self_assessment_controls (self_assessment_id, requirement_id, maturity_level, implementation_status, evidence_description, control_effectiveness, improvement_opportunities, action_plan, responsible_owner, target_completion_date, comments, last_reviewed_date, reviewer_name) VALUES
(1, 1, 4, 'Fully Implemented', 'Comprehensive governance framework with board oversight', 'Fully Effective', 'Enhance governance metrics and reporting', 'Implement advanced governance dashboards', 'CISO', '2024-06-30', 'Excellent governance maturity', '2024-03-15', 'Chief Risk Officer'),
(1, 2, 4, 'Largely Implemented', 'Risk management framework with regular assessments', 'Largely Effective', 'Implement quantitative risk analysis', 'Deploy risk quantification tools', 'Risk Manager', '2024-08-31', 'Good risk management foundation', '2024-03-20', 'Chief Risk Officer'),
(1, 3, 5, 'Fully Implemented', 'Comprehensive data classification with automated labeling', 'Fully Effective', 'Extend classification to cloud environments', 'Implement cloud data classification', 'Data Protection Officer', '2024-07-31', 'Leading practice in data classification', '2024-03-25', 'Chief Risk Officer'),
(1, 4, 3, 'Partially Implemented', 'Encryption standards defined, implementation in progress', 'Partially Effective', 'Complete encryption deployment', 'Accelerate encryption implementation', 'IT Security Manager', '2024-09-30', 'Encryption rollout ongoing', '2024-03-30', 'Chief Risk Officer'),
(1, 5, 4, 'Largely Implemented', 'IAM system with role-based access controls', 'Largely Effective', 'Implement privileged access management', 'Deploy PAM solution', 'Identity Manager', '2024-10-31', 'Strong access control foundation', '2024-03-28', 'Chief Risk Officer'),
(2, 1, 4, 'Fully Implemented', 'Governance framework continuously improved', 'Fully Effective', 'Implement AI-driven governance insights', 'Explore AI governance tools', 'CISO', '2024-09-30', 'Governance excellence maintained', '2024-06-15', 'Chief Risk Officer'),
(2, 2, 4, 'Largely Implemented', 'Enhanced risk management with automation', 'Largely Effective', 'Implement predictive risk analytics', 'Deploy predictive risk tools', 'Risk Manager', '2024-11-30', 'Risk management maturity improving', '2024-06-20', 'Chief Risk Officer');

-- Insert sample MICA gap analysis
INSERT INTO mica_gap_analysis (analysis_name, organization_id, assessment_id, analysis_date, analyst_name, status, overall_gap_score, critical_gaps_count, high_gaps_count, medium_gaps_count, low_gaps_count, executive_summary, methodology_used, key_findings, priority_recommendations, resource_requirements, timeline_estimate, budget_estimate, business_impact_assessment, risk_implications, next_steps, created_by) VALUES
('MICA Compliance Gap Analysis 2024', 1, 1, '2024-02-15', 'Senior Risk Analyst', 'Completed', 24.8, 2, 5, 8, 12, 'Comprehensive gap analysis identifies key areas for compliance enhancement', 'MICA gap analysis methodology with risk-based prioritization', 'Network security gaps, incomplete automation, documentation needs', 'Prioritize network security and automation investments', '15 FTE months, external consulting support', '12-18 months for full remediation', 750000.00, 'Medium business impact with manageable implementation', 'Moderate compliance risk requiring structured remediation', 'Develop detailed remediation roadmap and secure budget approval', 1);

-- Insert sample MICA gap analysis details
INSERT INTO mica_gap_analysis_details (gap_analysis_id, requirement_id, current_state_description, target_state_description, gap_description, gap_severity, business_impact, technical_complexity, estimated_effort_hours, estimated_cost, recommended_solution, implementation_approach, dependencies, risks_and_challenges, success_criteria, priority_ranking, target_completion_date, assigned_owner, status) VALUES
(1, 4, 'Basic encryption in place for some systems', 'Comprehensive encryption across all systems and data', 'Inconsistent encryption implementation across infrastructure', 'High', 'High', 'Medium', 480, 125000.00, 'Implement enterprise encryption management platform', 'Phased rollout starting with critical systems', 'Key management infrastructure, staff training', 'Legacy system compatibility, performance impact', 'All data encrypted at rest and in transit', 1, '2024-09-30', 'IT Security Manager', 'Planned'),
(1, 8, 'Basic network monitoring in place', 'Advanced network security monitoring with AI/ML capabilities', 'Limited network security monitoring and threat detection', 'High', 'High', 'High', 720, 200000.00, 'Deploy advanced SIEM with network behavior analytics', 'Implement SIEM platform with gradual capability enhancement', 'Network infrastructure upgrades, security team training', 'Integration complexity, false positive management', 'Real-time threat detection and automated response', 2, '2024-11-30', 'Network Security Manager', 'In Progress'),
(1, 9, 'Manual vulnerability scanning', 'Automated vulnerability management with continuous monitoring', 'Limited automation in vulnerability management process', 'Medium', 'Medium', 'Medium', 320, 75000.00, 'Implement automated vulnerability management platform', 'Deploy vulnerability management tools with workflow automation', 'Asset inventory completion, process standardization', 'Tool integration, workflow optimization', 'Automated vulnerability detection and remediation tracking', 3, '2024-08-31', 'Vulnerability Manager', 'Identified'),
(1, 5, 'Basic incident response procedures', 'Automated incident response with orchestration capabilities', 'Manual incident response processes with limited automation', 'Medium', 'Medium', 'High', 560, 150000.00, 'Implement security orchestration and automated response (SOAR)', 'Deploy SOAR platform with playbook automation', 'Incident response team training, playbook development', 'Process standardization, tool integration complexity', 'Automated incident detection, response, and recovery', 4, '2024-10-31', 'Incident Response Manager', 'Analyzed'),
(1, 6, 'Basic security awareness training', 'Comprehensive security awareness program with simulation', 'Limited security awareness training and phishing simulation', 'Medium', 'Low', 'Low', 240, 50000.00, 'Implement comprehensive security awareness platform', 'Deploy training platform with regular phishing simulations', 'HR coordination, content development', 'User engagement, training effectiveness measurement', 'Reduced security incidents from human error', 5, '2024-07-31', 'Security Awareness Manager', 'Identified');

-- Insert sample MICA remediation plans
INSERT INTO mica_remediation_plans (assessment_id, requirement_id, gap_description, remediation_action, priority, status, assigned_to, target_date, estimated_cost, business_impact, technical_complexity, dependencies, progress_notes) VALUES
(1, 4, 'Inconsistent encryption implementation', 'Deploy enterprise encryption management platform', 'High', 'In Progress', 'IT Security Manager', '2024-09-30', 125000.00, 'Significant improvement in data protection posture', 'Medium', 'Key management infrastructure, staff training', 'Encryption platform selected, implementation 40% complete'),
(1, 8, 'Limited network security monitoring', 'Implement advanced SIEM with network behavior analytics', 'High', 'In Progress', 'Network Security Manager', '2024-11-30', 200000.00, 'Enhanced threat detection and response capabilities', 'High', 'Network infrastructure upgrades, security team training', 'SIEM platform deployed, configuration 60% complete'),
(1, 9, 'Manual vulnerability management', 'Deploy automated vulnerability management platform', 'Medium', 'Open', 'Vulnerability Manager', '2024-08-31', 75000.00, 'Improved vulnerability detection and remediation efficiency', 'Medium', 'Asset inventory completion, process standardization', 'Requirements gathering phase, vendor evaluation in progress'),
(1, 5, 'Manual incident response processes', 'Implement security orchestration and automated response (SOAR)', 'Medium', 'Open', 'Incident Response Manager', '2024-10-31', 150000.00, 'Faster incident response and reduced manual effort', 'High', 'Incident response team training, playbook development', 'Initial planning phase, budget approval pending'),
(1, 6, 'Limited security awareness training', 'Deploy comprehensive security awareness platform', 'Low', 'Open', 'Security Awareness Manager', '2024-07-31', 50000.00, 'Reduced security incidents from human error', 'Low', 'HR coordination, content development', 'Platform evaluation in progress, content strategy being developed');
