-- Insert sample assessment data
INSERT INTO assessments (
    assessment_id,
    assessment_name,
    assessment_type,
    assessment_scope,
    assessment_status,
    start_date,
    end_date,
    assigned_assessor,
    assessment_methodology,
    compliance_framework,
    assessment_priority,
    completion_percentage,
    findings_count,
    high_risk_findings,
    medium_risk_findings,
    low_risk_findings
) VALUES 
(
    'ASS-2024-001',
    'Annual ISO 27001 Compliance Assessment',
    'Internal Audit',
    'Information security management system across all business units',
    'In Progress',
    '2024-01-15',
    '2024-03-15',
    'Sarah Johnson',
    'ISO 27001:2013 standard requirements assessment',
    'ISO 27001',
    'High',
    65,
    12,
    3,
    6,
    3
),
(
    'ASS-2024-002',
    'Network Infrastructure Security Review',
    'Security Review',
    'Network infrastructure, firewalls, and access controls',
    'Completed',
    '2024-02-01',
    '2024-02-28',
    'Michael Chen',
    'NIST Cybersecurity Framework assessment',
    'NIST CSF',
    'Critical',
    100,
    8,
    2,
    4,
    2
),
(
    'ASS-2024-003',
    'Third-Party Vendor Risk Assessment',
    'Third-Party Assessment',
    'Critical vendor security posture evaluation',
    'Planning',
    '2024-03-01',
    '2024-04-30',
    'Emily Rodriguez',
    'Vendor risk assessment questionnaire and on-site review',
    'Custom Framework',
    'High',
    0,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-004',
    'HIPAA Compliance Gap Analysis',
    'Compliance Review',
    'Healthcare data protection and privacy controls',
    'Under Review',
    '2024-01-20',
    '2024-03-20',
    'David Kim',
    'HIPAA Security and Privacy Rule assessment',
    'HIPAA',
    'Critical',
    85,
    15,
    5,
    7,
    3
),
(
    'ASS-2024-005',
    'Application Security Assessment',
    'Vulnerability Assessment',
    'Web applications and mobile applications security testing',
    'In Progress',
    '2024-02-15',
    '2024-04-15',
    'Lisa Wang',
    'OWASP Top 10 and secure code review',
    'NIST CSF',
    'High',
    40,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-006',
    'SOC 2 Type II Readiness Assessment',
    'External Audit',
    'Service organization controls for security, availability, and confidentiality',
    'Planning',
    '2024-04-01',
    '2024-06-30',
    'Robert Taylor',
    'SOC 2 Trust Services Criteria evaluation',
    'SOC 2',
    'Critical',
    0,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-007',
    'Cloud Security Posture Assessment',
    'Security Review',
    'AWS cloud infrastructure and services security configuration',
    'In Progress',
    '2024-02-10',
    '2024-03-25',
    'Jennifer Martinez',
    'Cloud Security Alliance (CSA) framework',
    'NIST CSF',
    'High',
    55,
    6,
    1,
    3,
    2
),
(
    'ASS-2024-008',
    'Data Privacy Impact Assessment',
    'Compliance Review',
    'Personal data processing activities and GDPR compliance',
    'Completed',
    '2024-01-05',
    '2024-02-05',
    'Thomas Anderson',
    'GDPR Article 35 DPIA methodology',
    'GDPR',
    'Medium',
    100,
    4,
    0,
    2,
    2
),
(
    'ASS-2024-009',
    'Penetration Testing - External',
    'Penetration Testing',
    'External network perimeter and web applications',
    'On Hold',
    '2024-03-15',
    '2024-04-15',
    'Alex Thompson',
    'OWASP Testing Guide and NIST SP 800-115',
    'Custom Framework',
    'Critical',
    25,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-010',
    'Business Continuity Plan Assessment',
    'Internal Audit',
    'Business continuity and disaster recovery procedures',
    'Planning',
    '2024-04-15',
    '2024-06-15',
    'Maria Garcia',
    'ISO 22301 business continuity management',
    'ISO 27001',
    'Medium',
    0,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-011',
    'Mobile Device Management Review',
    'Security Review',
    'Mobile device security policies and MDM implementation',
    'In Progress',
    '2024-02-20',
    '2024-03-30',
    'Kevin Lee',
    'NIST SP 800-124 mobile device security guidelines',
    'NIST CSF',
    'Medium',
    70,
    5,
    1,
    2,
    2
),
(
    'ASS-2024-012',
    'PCI DSS Compliance Assessment',
    'Compliance Review',
    'Payment card data security standards compliance',
    'Completed',
    '2024-01-10',
    '2024-02-20',
    'Rachel Green',
    'PCI DSS v4.0 requirements assessment',
    'PCI DSS',
    'Critical',
    100,
    7,
    2,
    3,
    2
),
(
    'ASS-2024-013',
    'Identity and Access Management Audit',
    'Internal Audit',
    'User access controls, privileged accounts, and identity governance',
    'Under Review',
    '2024-02-05',
    '2024-03-15',
    'James Wilson',
    'NIST SP 800-63 digital identity guidelines',
    'NIST CSF',
    'High',
    90,
    9,
    2,
    4,
    3
),
(
    'ASS-2024-014',
    'Incident Response Plan Testing',
    'Security Review',
    'Incident response procedures and team readiness',
    'Planning',
    '2024-05-01',
    '2024-05-31',
    'Amanda Brown',
    'NIST SP 800-61 incident handling guide',
    'NIST CSF',
    'High',
    0,
    0,
    0,
    0,
    0
),
(
    'ASS-2024-015',
    'Supply Chain Security Assessment',
    'Third-Party Assessment',
    'Supplier security requirements and vendor management',
    'In Progress',
    '2024-03-01',
    '2024-05-01',
    'Christopher Davis',
    'NIST SP 800-161 supply chain risk management',
    'NIST CSF',
    'Medium',
    30,
    0,
    0,
    0,
    0
)
ON CONFLICT (assessment_id) DO NOTHING;
