-- NIS2 Gap Analysis Table
-- Create table for NIS2 compliance gap analysis

CREATE TABLE IF NOT EXISTS nis2_gap_analysis (
    id SERIAL PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    control_id VARCHAR(20) NOT NULL,
    control_name VARCHAR(200) NOT NULL,
    current_status VARCHAR(50) NOT NULL, -- Not Implemented, Partially Implemented, Implemented
    target_status VARCHAR(50) NOT NULL, -- Implemented, Advanced Implementation
    gap_severity VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    business_impact VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    implementation_effort VARCHAR(20) NOT NULL, -- Low, Medium, High, Very High
    estimated_cost DECIMAL(12,2) DEFAULT 0,
    timeline_months INTEGER DEFAULT 6,
    responsible_party VARCHAR(200),
    dependencies TEXT,
    risk_if_not_addressed TEXT,
    priority_score INTEGER DEFAULT 5, -- 1-10 scale
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample NIS2 gap analysis data
INSERT INTO nis2_gap_analysis (
    domain, 
    control_id, 
    control_name, 
    current_status, 
    target_status, 
    gap_severity, 
    business_impact, 
    implementation_effort, 
    estimated_cost, 
    timeline_months, 
    responsible_party, 
    dependencies, 
    risk_if_not_addressed, 
    priority_score
) VALUES 
(
    'Incident Handling', 
    'IH-01', 
    'Incident Response Plan', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Medium', 
    25000.00, 
    4, 
    'CISO Office', 
    'Legal review, staff training, authority coordination', 
    'Delayed incident response, regulatory non-compliance, potential fines', 
    8
),
(
    'Supply Chain Security', 
    'SC-01', 
    'Supplier Risk Assessment', 
    'Not Implemented', 
    'Implemented', 
    'Critical', 
    'High', 
    'High', 
    50000.00, 
    8, 
    'Procurement & Risk Teams', 
    'Supplier cooperation, assessment tools, legal agreements', 
    'Supply chain attacks, third-party breaches, operational disruption', 
    9
),
(
    'Network and Information Systems Security', 
    'NS-01', 
    'Network Architecture Security', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'Critical', 
    'Very High', 
    150000.00, 
    12, 
    'IT Infrastructure Team', 
    'Network redesign, hardware procurement, system migration', 
    'Lateral movement in breaches, critical system compromise', 
    9
),
(
    'Cybersecurity Measures', 
    'CM-01', 
    'Access Control Management', 
    'Partially Implemented', 
    'Implemented', 
    'Critical', 
    'Critical', 
    'High', 
    75000.00, 
    6, 
    'Identity & Access Management Team', 
    'MFA deployment, legacy system integration, user training', 
    'Unauthorized access, privilege escalation, data breaches', 
    10
),
(
    'Network and Information Systems Security', 
    'NS-04', 
    'Security Monitoring', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Very High', 
    200000.00, 
    10, 
    'Security Operations Center', 
    'SIEM platform, staff training, integration with existing tools', 
    'Undetected threats, delayed incident response, compliance gaps', 
    8
),
(
    'Business Continuity', 
    'BC-01', 
    'Business Continuity Plan', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    30000.00, 
    5, 
    'Business Continuity Manager', 
    'Business impact analysis, recovery procedures, testing', 
    'Extended downtime, business disruption, revenue loss', 
    7
),
(
    'Risk Management', 
    'RM-02', 
    'Risk Assessment Methodology', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Medium', 
    20000.00, 
    4, 
    'Risk Management Team', 
    'Risk assessment tools, staff training, process documentation', 
    'Inadequate risk identification, poor risk decisions', 
    6
),
(
    'Corporate Governance', 
    'CG-02', 
    'Board Oversight', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Low', 
    10000.00, 
    3, 
    'Governance Office', 
    'Board training, reporting templates, governance framework', 
    'Lack of strategic oversight, governance gaps', 
    5
),
(
    'Policies on Vulnerability Disclosure', 
    'VD-01', 
    'Vulnerability Disclosure Policy', 
    'Not Implemented', 
    'Implemented', 
    'Low', 
    'Medium', 
    'Low', 
    5000.00, 
    2, 
    'Security Team', 
    'Legal review, communication channels, response procedures', 
    'Uncoordinated vulnerability disclosure, reputation risk', 
    4
),
(
    'Crisis Management', 
    'CR-01', 
    'Crisis Management Plan', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    25000.00, 
    6, 
    'Crisis Management Team', 
    'Communication plans, stakeholder mapping, training', 
    'Poor crisis response, stakeholder confusion, reputation damage', 
    6
),
(
    'Cybersecurity Measures', 
    'CM-03', 
    'Cryptography and Key Management', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'High', 
    80000.00, 
    8, 
    'Security Team', 
    'Encryption solutions, key management system, policy development', 
    'Data exposure, regulatory non-compliance, privacy breaches', 
    8
),
(
    'Network and Information Systems Security', 
    'NS-03', 
    'Vulnerability Management', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    40000.00, 
    5, 
    'Security Operations Team', 
    'Scanning tools, patch management, risk prioritization', 
    'Unpatched vulnerabilities, system compromise', 
    7
),
(
    'Supply Chain Security', 
    'SC-03', 
    'Supplier Monitoring', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'Medium', 
    'High', 
    60000.00, 
    9, 
    'Procurement Team', 
    'Monitoring tools, supplier agreements, assessment processes', 
    'Supply chain compromise, third-party incidents', 
    7
),
(
    'Incident Handling', 
    'IH-04', 
    'Incident Recovery', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    35000.00, 
    4, 
    'Incident Response Team', 
    'Recovery procedures, testing, lessons learned process', 
    'Prolonged recovery, repeated incidents', 
    6
),
(
    'Security in Network and Information Systems Acquisition', 
    'SA-03', 
    'Secure Development Lifecycle', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'High', 
    70000.00, 
    10, 
    'Development Team', 
    'SDLC tools, security training, code review processes', 
    'Insecure applications, development vulnerabilities', 
    5
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_nis2_gap_analysis_domain ON nis2_gap_analysis(domain);
CREATE INDEX IF NOT EXISTS idx_nis2_gap_analysis_severity ON nis2_gap_analysis(gap_severity);
CREATE INDEX IF NOT EXISTS idx_nis2_gap_analysis_priority ON nis2_gap_analysis(priority_score);
CREATE INDEX IF NOT EXISTS idx_nis2_gap_analysis_status ON nis2_gap_analysis(current_status);
CREATE INDEX IF NOT EXISTS idx_nis2_gap_analysis_impact ON nis2_gap_analysis(business_impact);
