-- Qatar NIA Gap Analysis Table
-- Create table for Qatar NIA compliance gap analysis

CREATE TABLE IF NOT EXISTS qatar_nia_gap_analysis (
    id SERIAL PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    control_id VARCHAR(20) NOT NULL,
    control_name VARCHAR(200) NOT NULL,
    current_status VARCHAR(50) NOT NULL, -- Not Implemented, Partially Implemented, Implemented
    target_status VARCHAR(50) NOT NULL, -- Implemented, Advanced Implementation
    gap_severity VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    business_impact VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    implementation_effort VARCHAR(20) NOT NULL, -- Low, Medium, High, Very High
    estimated_cost DECIMAL(12,2) DEFAULT 0,
    timeline_months INTEGER DEFAULT 6,
    responsible_party VARCHAR(200),
    dependencies TEXT,
    risk_if_not_addressed TEXT,
    priority_score INTEGER DEFAULT 5, -- 1-10 scale
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample Qatar NIA gap analysis data
INSERT INTO qatar_nia_gap_analysis (
    domain, 
    control_id, 
    control_name, 
    current_status, 
    target_status, 
    gap_severity, 
    business_impact, 
    implementation_effort, 
    estimated_cost, 
    timeline_months, 
    responsible_party, 
    dependencies, 
    risk_if_not_addressed, 
    priority_score
) VALUES 
(
    'Information Security Incident Management', 
    'IM-01', 
    'Management of Information Security Incidents and Improvements', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Medium', 
    30000.00, 
    4, 
    'CISO Office', 
    'Legal review, staff training, authority coordination procedures', 
    'Delayed incident response, regulatory non-compliance, potential penalties', 
    8
),
(
    'Supplier Relationships', 
    'SR-01', 
    'Information Security Policy for Supplier Relationships', 
    'Not Implemented', 
    'Implemented', 
    'Critical', 
    'High', 
    'High', 
    55000.00, 
    8, 
    'Procurement & Risk Teams', 
    'Supplier cooperation, assessment tools, legal agreements, monitoring systems', 
    'Supply chain attacks, third-party breaches, operational disruption', 
    9
),
(
    'Cryptography', 
    'CR-02', 
    'Key Management', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'Critical', 
    'Very High', 
    180000.00, 
    12, 
    'Cryptography Team', 
    'Key management system, hardware security modules, integration with existing systems', 
    'Cryptographic key compromise, data exposure, regulatory violations', 
    9
),
(
    'Access Control', 
    'AC-05', 
    'System and Application Access Control', 
    'Partially Implemented', 
    'Implemented', 
    'Critical', 
    'Critical', 
    'High', 
    95000.00, 
    6, 
    'Identity & Access Management Team', 
    'Role-based access control system, integration with applications, user training', 
    'Unauthorized access, privilege escalation, data breaches', 
    10
),
(
    'Communications Security', 
    'CS-03', 
    'Segregation in Networks', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Very High', 
    220000.00, 
    10, 
    'Network Security Team', 
    'Network redesign, segmentation tools, firewall upgrades, testing', 
    'Lateral movement in breaches, critical system compromise', 
    8
),
(
    'Business Continuity', 
    'BC-01', 
    'Information Security Continuity', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    40000.00, 
    5, 
    'Business Continuity Team', 
    'Business impact analysis, recovery procedures, testing framework', 
    'Extended downtime, business disruption, revenue loss', 
    7
),
(
    'Risk Management', 
    'RM-02', 
    'Information Security Risk Assessment', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Medium', 
    25000.00, 
    4, 
    'Risk Management Team', 
    'Risk assessment tools, staff training, process documentation', 
    'Inadequate risk identification, poor risk decisions', 
    6
),
(
    'Information Security Governance', 
    'ISG-03', 
    'Management Direction for Information Security', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Low', 
    12000.00, 
    3, 
    'Governance Office', 
    'Management training, reporting templates, governance framework', 
    'Lack of strategic oversight, governance gaps', 
    5
),
(
    'Physical and Environmental Security', 
    'PE-02', 
    'Physical Entry Controls', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'Medium', 
    'Medium', 
    35000.00, 
    6, 
    'Facilities Security Team', 
    'Access control systems, biometric readers, visitor management', 
    'Unauthorized physical access, equipment theft, facility compromise', 
    7
),
(
    'Operations Security', 
    'OS-05', 
    'Protection from Malware', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    45000.00, 
    5, 
    'IT Operations Team', 
    'Advanced anti-malware solutions, endpoint protection, user training', 
    'Malware infections, system compromise, data loss', 
    6
),
(
    'Asset Management', 
    'AM-02', 
    'Information Classification', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Medium', 
    20000.00, 
    4, 
    'Asset Management Team', 
    'Classification scheme, labeling tools, staff training', 
    'Inappropriate information handling, data exposure', 
    5
),
(
    'System Acquisition and Development', 
    'SA-03', 
    'System Security Testing', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'High', 
    75000.00, 
    8, 
    'Development Team', 
    'Security testing tools, penetration testing services, training', 
    'Insecure applications, development vulnerabilities', 
    6
),
(
    'Compliance', 
    'CO-04', 
    'Privacy and Protection of Personally Identifiable Information', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'Critical', 
    'High', 
    85000.00, 
    9, 
    'Compliance Team', 
    'Privacy framework, data governance tools, legal consultation', 
    'Privacy violations, regulatory penalties, reputation damage', 
    8
),
(
    'Communications Security', 
    'CS-01', 
    'Network Security Management', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    50000.00, 
    6, 
    'Network Security Team', 
    'Network monitoring tools, security controls, staff training', 
    'Network vulnerabilities, unauthorized access', 
    7
),
(
    'Supplier Relationships', 
    'SR-04', 
    'Monitoring and Review of Supplier Services', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'Medium', 
    'High', 
    65000.00, 
    9, 
    'Procurement Team', 
    'Monitoring tools, supplier agreements, assessment processes', 
    'Supply chain compromise, third-party incidents', 
    7
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_qatar_nia_gap_analysis_domain ON qatar_nia_gap_analysis(domain);
CREATE INDEX IF NOT EXISTS idx_qatar_nia_gap_analysis_severity ON qatar_nia_gap_analysis(gap_severity);
CREATE INDEX IF NOT EXISTS idx_qatar_nia_gap_analysis_priority ON qatar_nia_gap_analysis(priority_score);
CREATE INDEX IF NOT EXISTS idx_qatar_nia_gap_analysis_status ON qatar_nia_gap_analysis(current_status);
CREATE INDEX IF NOT EXISTS idx_qatar_nia_gap_analysis_impact ON qatar_nia_gap_analysis(business_impact);
