-- DORA Gap Analysis Table
-- Create table for DORA compliance gap analysis

CREATE TABLE IF NOT EXISTS dora_gap_analysis (
    id SERIAL PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    control_id VARCHAR(20) NOT NULL,
    control_name VARCHAR(200) NOT NULL,
    current_status VARCHAR(50) NOT NULL, -- Not Implemented, Partially Implemented, Implemented
    target_status VARCHAR(50) NOT NULL, -- Implemented, Advanced Implementation
    gap_severity VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    business_impact VARCHAR(20) NOT NULL, -- Critical, High, Medium, Low
    implementation_effort VARCHAR(20) NOT NULL, -- Low, Medium, High, Very High
    estimated_cost DECIMAL(12,2) DEFAULT 0,
    timeline_months INTEGER DEFAULT 6,
    responsible_party VARCHAR(200),
    dependencies TEXT,
    risk_if_not_addressed TEXT,
    priority_score INTEGER DEFAULT 5, -- 1-10 scale
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample DORA gap analysis data
INSERT INTO dora_gap_analysis (
    domain, 
    control_id, 
    control_name, 
    current_status, 
    target_status, 
    gap_severity, 
    business_impact, 
    implementation_effort, 
    estimated_cost, 
    timeline_months, 
    responsible_party, 
    dependencies, 
    risk_if_not_addressed, 
    priority_score
) VALUES 
(
    'Digital Operational Resilience Testing', 
    'DORT-01', 
    'Testing Strategy', 
    'Not Implemented', 
    'Implemented', 
    'Critical', 
    'High', 
    'Very High', 
    150000.00, 
    12, 
    'IT Security Team', 
    'External testing vendors, regulatory approval, staff training', 
    'Inability to validate operational resilience, regulatory non-compliance, potential system failures', 
    9
),
(
    'Managing ICT Third-party Risk', 
    'ICT-TPR-02', 
    'Due Diligence', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'Critical', 
    'High', 
    75000.00, 
    8, 
    'Third-party Risk Team', 
    'Legal review, vendor cooperation, risk assessment tools', 
    'Third-party security incidents, supply chain disruption, regulatory penalties', 
    8
),
(
    'ICT-related Incident Management', 
    'ICT-IM-05', 
    'External Incident Reporting', 
    'Partially Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Medium', 
    35000.00, 
    6, 
    'Incident Response Team', 
    'Regulatory guidance, legal review, reporting templates', 
    'Regulatory non-compliance, delayed incident response, potential fines', 
    8
),
(
    'ICT Security Controls', 
    'ICT-SC-05', 
    'Security Monitoring', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Very High', 
    200000.00, 
    10, 
    'Security Operations Center', 
    'SIEM platform, staff training, integration with existing tools', 
    'Undetected security threats, delayed incident response, data breaches', 
    8
),
(
    'ICT Governance and Strategy', 
    'ICT-GS-03', 
    'Board Oversight', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Medium', 
    25000.00, 
    4, 
    'ICT Governance Office', 
    'Board training, governance framework, reporting procedures', 
    'Inadequate strategic oversight, governance gaps, regulatory concerns', 
    6
),
(
    'ICT Business Continuity', 
    'ICT-BC-04', 
    'Alternative Sites', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'Critical', 
    'Very High', 
    300000.00, 
    15, 
    'Business Continuity Team', 
    'Site selection, infrastructure setup, data replication, testing', 
    'Extended downtime, business disruption, customer impact', 
    7
),
(
    'ICT Risk Management', 
    'ICT-RM-04', 
    'ICT Risk Monitoring', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'High', 
    80000.00, 
    8, 
    'ICT Risk Management Team', 
    'Risk monitoring tools, dashboard development, integration', 
    'Inadequate risk visibility, delayed risk response, compliance gaps', 
    6
),
(
    'ICT Asset Management', 
    'ICT-AM-04', 
    'Configuration Management', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'High', 
    90000.00, 
    9, 
    'IT Asset Management Team', 
    'Configuration management tools, process definition, staff training', 
    'Configuration drift, security vulnerabilities, operational issues', 
    5
),
(
    'Information and Intelligence Sharing', 
    'IIS-02', 
    'Threat Intelligence', 
    'Not Implemented', 
    'Implemented', 
    'Low', 
    'Medium', 
    'Medium', 
    45000.00, 
    6, 
    'Threat Intelligence Team', 
    'Threat intelligence platform, data feeds, analysis capabilities', 
    'Limited threat awareness, reactive security posture', 
    4
),
(
    'Digital Operational Resilience Testing', 
    'DORT-04', 
    'Red Team Testing', 
    'Not Implemented', 
    'Implemented', 
    'High', 
    'High', 
    'Very High', 
    120000.00, 
    12, 
    'IT Security Team', 
    'External red team specialists, testing scope definition, remediation planning', 
    'Unidentified vulnerabilities, inadequate defense testing', 
    7
),
(
    'Managing ICT Third-party Risk', 
    'ICT-TPR-06', 
    'Exit Strategies', 
    'Not Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'High', 
    60000.00, 
    10, 
    'Third-party Risk Team', 
    'Legal agreements, alternative providers, transition planning', 
    'Vendor lock-in, service disruption, increased costs', 
    6
),
(
    'ICT Security Controls', 
    'ICT-SC-02', 
    'Cryptography', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'High', 
    70000.00, 
    7, 
    'Information Security Team', 
    'Encryption solutions, key management, policy development', 
    'Data exposure, regulatory non-compliance, privacy breaches', 
    7
),
(
    'ICT-related Incident Management', 
    'ICT-IM-06', 
    'Incident Recovery', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'High', 
    'Medium', 
    40000.00, 
    5, 
    'Incident Response Team', 
    'Recovery procedures, testing, coordination with business continuity', 
    'Prolonged recovery times, business impact, customer dissatisfaction', 
    6
),
(
    'ICT Business Continuity', 
    'ICT-BC-05', 
    'Testing and Exercises', 
    'Partially Implemented', 
    'Implemented', 
    'Medium', 
    'Medium', 
    'Medium', 
    30000.00, 
    4, 
    'Business Continuity Team', 
    'Testing scenarios, exercise planning, result analysis', 
    'Untested procedures, recovery failures, compliance gaps', 
    5
),
(
    'ICT Asset Management', 
    'ICT-AM-03', 
    'Asset Lifecycle', 
    'Partially Implemented', 
    'Implemented', 
    'Low', 
    'Medium', 
    'Medium', 
    35000.00, 
    6, 
    'IT Asset Management Team', 
    'Lifecycle management processes, tools integration, staff training', 
    'Inefficient asset utilization, security risks, compliance issues', 
    4
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_dora_gap_analysis_domain ON dora_gap_analysis(domain);
CREATE INDEX IF NOT EXISTS idx_dora_gap_analysis_severity ON dora_gap_analysis(gap_severity);
CREATE INDEX IF NOT EXISTS idx_dora_gap_analysis_priority ON dora_gap_analysis(priority_score);
CREATE INDEX IF NOT EXISTS idx_dora_gap_analysis_status ON dora_gap_analysis(current_status);
CREATE INDEX IF NOT EXISTS idx_dora_gap_analysis_impact ON dora_gap_analysis(business_impact);
