-- Insert sample sphere AI risks data
INSERT INTO sphere_ai_risks (
    title, description, category, likelihood, impact, risk_owner, business_unit,
    assets, threat_sources, vulnerabilities, existing_controls,
    ai_risk_score, ai_risk_level, ai_confidence, ai_recommendations, ai_similar_risks, ai_predicted_trends,
    status, created_by
) VALUES 
(
    'Ransomware Attack on Critical Infrastructure',
    'Potential ransomware attack targeting critical business infrastructure including servers, databases, and network equipment. This could result in complete business disruption and significant financial losses.',
    'Infrastructure Security',
    4, 5,
    'John Smith',
    'IT Operations',
    '["Database Servers", "Web Servers", "Network Infrastructure", "Backup Systems"]',
    '["Cybercriminal Groups", "Advanced Persistent Threats", "Malicious Email Attachments"]',
    '["Unpatched Systems", "Weak Email Security", "Insufficient Backup Procedures", "Limited Network Segmentation"]',
    '["Firewall", "Antivirus Software", "Email Filtering", "Regular Backups"]',
    8.5, 'Critical', 92,
    '["Implement advanced endpoint detection and response (EDR)", "Establish comprehensive backup and recovery procedures", "Deploy network segmentation", "Conduct regular penetration testing", "Implement zero-trust architecture"]',
    '["Advanced Persistent Threat Attacks", "Data Breach Incidents", "Business Email Compromise", "Supply Chain Attacks"]',
    '["Increasing sophistication of ransomware attacks", "Growing targeting of critical infrastructure", "Rise in double extortion tactics", "Expansion of ransomware-as-a-service models"]',
    'Under Review',
    'AI Risk Analyst'
),
(
    'Data Breach via Phishing Attack',
    'Risk of sensitive customer data exposure through successful phishing attacks targeting employees with access to customer databases and personal information.',
    'Data Security',
    3, 4,
    'Sarah Johnson',
    'Customer Services',
    '["Customer Database", "CRM System", "Employee Workstations", "Email System"]',
    '["Cybercriminals", "Social Engineers", "Malicious Email Campaigns"]',
    '["Insufficient Security Awareness", "Weak Email Authentication", "Lack of Multi-Factor Authentication", "Outdated Security Policies"]',
    '["Email Security Gateway", "Security Awareness Training", "Data Loss Prevention", "Access Controls"]',
    6.8, 'High', 87,
    '["Implement comprehensive security awareness training", "Deploy advanced email security solutions", "Establish multi-factor authentication", "Implement data classification and handling procedures", "Regular phishing simulation exercises"]',
    '["Business Email Compromise", "Credential Stuffing Attacks", "Social Engineering Attacks", "Insider Threats"]',
    '["Increasing use of AI in phishing attacks", "Growing sophistication of social engineering", "Rise in targeted spear-phishing campaigns", "Expansion of business email compromise tactics"]',
    'Approved',
    'AI Risk Analyst'
),
(
    'API Security Vulnerabilities',
    'Security vulnerabilities in customer-facing APIs that could lead to unauthorized access, data manipulation, or service disruption affecting business operations.',
    'Application Security',
    3, 3,
    'Mike Chen',
    'Development Team',
    '["Customer API", "Mobile Application", "Web Application", "Database Connections"]',
    '["Malicious Hackers", "Automated Attack Tools", "Insider Threats"]',
    '["Insufficient Input Validation", "Weak Authentication Mechanisms", "Lack of Rate Limiting", "Inadequate Logging and Monitoring"]',
    '["API Gateway", "Input Validation", "Authentication Tokens", "Basic Monitoring"]',
    5.2, 'Medium', 83,
    '["Implement comprehensive API security testing", "Deploy API gateway with advanced security features", "Establish proper authentication and authorization", "Implement rate limiting and throttling", "Enhanced API monitoring and logging"]',
    '["SQL Injection Attacks", "Cross-Site Scripting (XSS)", "Authentication Bypass", "Data Injection Attacks"]',
    '["Increasing attacks on API endpoints", "Growing complexity of API ecosystems", "Rise in automated API testing tools", "Expansion of microservices architectures"]',
    'Draft',
    'AI Risk Analyst'
),
(
    'Third-Party Vendor Data Breach',
    'Risk of data exposure through security incidents at third-party vendors who have access to sensitive business and customer information.',
    'Third-party Risk',
    2, 4,
    'Lisa Wang',
    'Procurement',
    '["Vendor Systems", "Shared Databases", "Integration Points", "Customer Data"]',
    '["Vendor Security Incidents", "Supply Chain Attacks", "Compromised Vendor Accounts"]',
    '["Limited Vendor Security Oversight", "Insufficient Due Diligence", "Weak Contractual Security Requirements", "Lack of Continuous Monitoring"]',
    '["Vendor Assessments", "Contractual Security Requirements", "Limited Access Controls", "Basic Monitoring"]',
    6.0, 'Medium', 79,
    '["Implement comprehensive vendor risk management program", "Establish continuous monitoring of vendor security posture", "Require security certifications from critical vendors", "Implement vendor access controls and monitoring", "Regular vendor security assessments"]',
    '["Supply Chain Compromise", "Vendor Data Breach", "Cloud Service Provider Outages", "Integration Security Issues"]',
    '["Increasing attacks on supply chains", "Growing interconnectedness of business systems", "Rising regulatory focus on third-party risk", "Expansion of cloud service dependencies"]',
    'Under Review',
    'AI Risk Analyst'
),
(
    'Insider Threat - Privileged User Abuse',
    'Risk of malicious or negligent actions by privileged users with administrative access to critical systems and sensitive data.',
    'Human Resources',
    2, 4,
    'David Brown',
    'Human Resources',
    '["Administrative Systems", "Employee Records", "Financial Systems", "Customer Database"]',
    '["Malicious Insiders", "Negligent Employees", "Compromised Privileged Accounts"]',
    '["Excessive Privileged Access", "Insufficient Monitoring", "Lack of Segregation of Duties", "Inadequate Background Checks"]',
    '["Access Controls", "Background Checks", "Basic User Activity Monitoring", "HR Policies"]',
    5.8, 'Medium', 75,
    '["Implement privileged access management (PAM)", "Establish comprehensive user activity monitoring", "Implement segregation of duties", "Regular access reviews and certifications", "Enhanced background screening procedures"]',
    '["Privileged Account Abuse", "Data Theft by Employees", "Sabotage Incidents", "Negligent Data Exposure"]',
    '["Growing sophistication of insider threats", "Increasing remote work challenges", "Rise in privileged access abuse", "Expansion of insider threat detection tools"]',
    'Approved',
    'AI Risk Analyst'
),
(
    'Cloud Infrastructure Misconfiguration',
    'Risk of security vulnerabilities due to misconfigured cloud infrastructure settings, potentially exposing sensitive data and systems to unauthorized access.',
    'Infrastructure Security',
    3, 3,
    'Alex Rodriguez',
    'Cloud Operations',
    '["Cloud Storage", "Virtual Machines", "Network Configuration", "Identity Management"]',
    '["External Attackers", "Automated Scanning Tools", "Misconfiguration Exploitation"]',
    '["Complex Cloud Configurations", "Lack of Cloud Security Expertise", "Insufficient Configuration Management", "Inadequate Security Baselines"]',
    '["Cloud Security Policies", "Basic Configuration Management", "Access Controls", "Monitoring Tools"]',
    4.9, 'Medium', 81,
    '["Implement cloud security posture management (CSPM)", "Establish infrastructure as code (IaC) practices", "Deploy automated configuration scanning", "Implement cloud security baselines", "Regular cloud security assessments"]',
    '["Cloud Data Breaches", "Unauthorized Access", "Service Disruptions", "Compliance Violations"]',
    '["Increasing cloud adoption complexity", "Growing cloud security tool sophistication", "Rise in automated cloud attacks", "Expansion of multi-cloud environments"]',
    'Draft',
    'AI Risk Analyst'
),
(
    'Mobile Application Security Vulnerabilities',
    'Security weaknesses in mobile applications that could lead to unauthorized access to business data, user credentials, or backend systems.',
    'Application Security',
    2, 3,
    'Jennifer Lee',
    'Mobile Development',
    '["Mobile Applications", "User Devices", "Backend APIs", "User Data"]',
    '["Malicious App Developers", "Device Malware", "Network Attackers"]',
    '["Insecure Data Storage", "Weak Encryption", "Insufficient Transport Security", "Inadequate Authentication"]',
    '["Code Obfuscation", "Basic Encryption", "SSL/TLS", "App Store Reviews"]',
    4.2, 'Medium', 78,
    '["Implement mobile application security testing (MAST)", "Deploy mobile device management (MDM)", "Establish secure coding practices for mobile", "Implement certificate pinning", "Regular mobile security assessments"]',
    '["Mobile Malware", "App Store Attacks", "Device Compromise", "Man-in-the-Middle Attacks"]',
    '["Growing mobile attack sophistication", "Increasing BYOD security challenges", "Rise in mobile banking trojans", "Expansion of IoT device vulnerabilities"]',
    'Under Review',
    'AI Risk Analyst'
),
(
    'Compliance Violation - GDPR Data Processing',
    'Risk of violating GDPR regulations due to improper data processing, storage, or handling procedures, potentially resulting in significant fines and reputational damage.',
    'Compliance',
    2, 4,
    'Maria Garcia',
    'Legal & Compliance',
    '["Customer Data", "Processing Systems", "Data Storage", "Third-party Integrations"]',
    '["Regulatory Audits", "Data Subject Complaints", "Privacy Violations"]',
    '["Complex Data Flows", "Insufficient Data Mapping", "Lack of Consent Management", "Inadequate Data Retention Policies"]',
    '["Privacy Policies", "Consent Forms", "Data Retention Procedures", "Basic Data Protection Measures"]',
    5.5, 'Medium', 85,
    '["Implement comprehensive data mapping and classification", "Deploy privacy management tools", "Establish data subject rights procedures", "Implement privacy by design principles", "Regular compliance assessments and audits"]',
    '["Privacy Regulation Violations", "Data Subject Rights Violations", "Cross-border Data Transfer Issues", "Consent Management Failures"]',
    '["Increasing privacy regulation enforcement", "Growing data subject awareness", "Rise in privacy-focused technologies", "Expansion of global privacy regulations"]',
    'Approved',
    'AI Risk Analyst'
),
(
    'DDoS Attack on Web Services',
    'Risk of distributed denial of service attacks targeting customer-facing web services, potentially causing service disruption and business impact.',
    'Infrastructure Security',
    3, 3,
    'Robert Kim',
    'Network Operations',
    '["Web Servers", "Load Balancers", "CDN Services", "Network Infrastructure"]',
    '["Cybercriminal Groups", "Hacktivist Organizations", "Botnet Operators"]',
    '["Limited DDoS Protection", "Insufficient Bandwidth Capacity", "Lack of Traffic Analysis", "Inadequate Incident Response"]',
    '["Basic Firewall Rules", "Load Balancing", "CDN Services", "Network Monitoring"]',
    4.8, 'Medium', 82,
    '["Implement advanced DDoS protection services", "Establish traffic analysis and anomaly detection", "Deploy auto-scaling infrastructure", "Implement incident response procedures", "Regular DDoS simulation exercises"]',
    '["Network Infrastructure Attacks", "Service Availability Issues", "Bandwidth Exhaustion", "Application Layer Attacks"]',
    '["Increasing DDoS attack frequency", "Growing botnet sophistication", "Rise in application-layer attacks", "Expansion of IoT-based botnets"]',
    'Draft',
    'AI Risk Analyst'
),
(
    'Social Engineering Attack on Finance Team',
    'Risk of social engineering attacks targeting finance team members to authorize fraudulent transactions or disclose sensitive financial information.',
    'Human Resources',
    2, 4,
    'Thomas Wilson',
    'Finance',
    '["Financial Systems", "Banking Interfaces", "Employee Workstations", "Communication Systems"]',
    '["Social Engineers", "Fraudsters", "Business Email Compromise Groups"]',
    '["Insufficient Security Awareness", "Lack of Verification Procedures", "Inadequate Communication Security", "Limited Fraud Detection"]',
    '["Security Awareness Training", "Approval Workflows", "Email Security", "Basic Fraud Controls"]',
    5.7, 'Medium', 80,
    '["Implement comprehensive social engineering awareness training", "Establish multi-person authorization procedures", "Deploy advanced email security solutions", "Implement out-of-band verification procedures", "Regular social engineering simulation exercises"]',
    '["Business Email Compromise", "CEO Fraud", "Invoice Fraud", "Wire Transfer Fraud"]',
    '["Increasing social engineering sophistication", "Growing targeting of finance teams", "Rise in AI-generated social engineering", "Expansion of business email compromise tactics"]',
    'Under Review',
    'AI Risk Analyst'
);

-- Update statistics
ANALYZE sphere_ai_risks;
