-- Insert ISO 27002 Control Categories
INSERT INTO iso27002_control_categories (category_code, category_name, category_description) VALUES
('A.5', 'Information Security Policies', 'Management direction and support for information security in accordance with business requirements and relevant laws and regulations'),
('A.6', 'Organization of Information Security', 'To establish a management framework to initiate and control the implementation and operation of information security within the organization'),
('A.7', 'Human Resource Security', 'To ensure that employees and contractors understand their responsibilities and are suitable for the roles for which they are considered'),
('A.8', 'Asset Management', 'To identify organizational assets and define appropriate protection responsibilities'),
('A.9', 'Access Control', 'To limit access to information and information processing facilities'),
('A.10', 'Cryptography', 'To ensure proper and effective use of cryptography to protect the confidentiality, authenticity and/or integrity of information'),
('A.11', 'Physical and Environmental Security', 'To prevent unauthorized physical access, damage and interference to the organization''s information and information processing facilities'),
('A.12', 'Operations Security', 'To ensure correct and secure operations of information processing facilities'),
('A.13', 'Communications Security', 'To ensure the protection of information in networks and its supporting information processing facilities'),
('A.14', 'System Acquisition, Development and Maintenance', 'To ensure that information security is an integral part of information systems across the entire lifecycle'),
('A.15', 'Supplier Relationships', 'To ensure protection of the organization''s assets that is accessible by suppliers'),
('A.16', 'Information Security Incident Management', 'To ensure a consistent and effective approach to the management of information security incidents'),
('A.17', 'Information Security Aspects of Business Continuity Management', 'Information security continuity shall be embedded in the organization''s business continuity management systems'),
('A.18', 'Compliance', 'To avoid breaches of legal, statutory, regulatory or contractual obligations related to information security and of any security requirements')
ON CONFLICT (category_code) DO NOTHING;

-- Insert sample ISO 27002 Controls for each category
INSERT INTO iso27002_controls (control_code, control_title, control_description, control_guidance, category_id) VALUES
-- A.5 Information Security Policies
('A.5.1.1', 'Policies for information security', 'A set of policies for information security shall be defined, approved by management, published and communicated to employees and relevant external parties.', 'Information security policies should provide management direction and support for information security in accordance with business requirements and relevant laws and regulations.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.5')),
('A.5.1.2', 'Review of the policies for information security', 'The policies for information security shall be reviewed at planned intervals or if significant changes occur to ensure their continuing suitability, adequacy and effectiveness.', 'The review should include assessing opportunities for improvement and the need for changes to the approach to managing information security.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.5')),

-- A.6 Organization of Information Security
('A.6.1.1', 'Information security roles and responsibilities', 'All information security responsibilities shall be defined and allocated.', 'Allocation of information security responsibilities should be done in accordance with the information security policies.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.6')),
('A.6.1.2', 'Segregation of duties', 'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization''s assets.', 'Care should be taken that no single person can access, modify or use assets without authorization or detection.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.6')),
('A.6.1.3', 'Contact with authorities', 'Appropriate contacts with relevant authorities shall be maintained.', 'Organizations should have procedures in place that specify when and how authorities should be contacted, and how security incidents should be reported in a timely manner.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.6')),
('A.6.1.4', 'Contact with special interest groups', 'Appropriate contacts with special interest groups or other specialist security forums and professional associations shall be maintained.', 'Membership of information security forums and associations should be encouraged as a means of keeping up to date with best practices and being alert to emerging threats.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.6')),
('A.6.1.5', 'Information security in project management', 'Information security shall be addressed in project management, regardless of the type of the project.', 'Project management methodology should include information security considerations to ensure that information security is built into information systems.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.6')),

-- A.7 Human Resource Security
('A.7.1.1', 'Screening', 'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.', 'The organization should ensure that employees and contractors understand their responsibilities and are suitable for the roles for which they are considered.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.7')),
('A.7.1.2', 'Terms and conditions of employment', 'The contractual agreements with employees and contractors shall state their and the organization''s responsibilities for information security.', 'Terms and conditions of employment should include the employee''s information security responsibilities.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.7')),
('A.7.2.1', 'Management responsibilities', 'Management shall require all employees and contractors to apply information security in accordance with the established policies and procedures of the organization.', 'Management should ensure that employees and contractors are aware of and fulfill their information security responsibilities.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.7')),
('A.7.2.2', 'Information security awareness, education and training', 'All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function.', 'Information security education and training programme should be provided to all employees and contractors.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.7')),
('A.7.2.3', 'Disciplinary process', 'There shall be a formal and communicated disciplinary process in place to take action against employees who have committed an information security breach.', 'The disciplinary process should not be started without prior verification that an information security breach has occurred.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.7')),

-- A.8 Asset Management
('A.8.1.1', 'Inventory of assets', 'Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.', 'The organization should identify all assets and document their importance.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.8')),
('A.8.1.2', 'Ownership of assets', 'Assets maintained in the inventory shall be owned.', 'All assets should have an appointed owner, responsible for their appropriate protection throughout their lifecycle.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.8')),
('A.8.1.3', 'Acceptable use of assets', 'Rules for the acceptable use of information and of assets associated with information and information processing facilities shall be identified, documented and implemented.', 'All employees and external party users should follow the rules for the acceptable use of information and assets associated with information processing facilities.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.8')),
('A.8.1.4', 'Return of assets', 'All employees and external party users shall return all of the organizational assets in their possession upon termination of their employment, contract or agreement.', 'Employees and external party users should be made aware of their responsibilities for returning organizational assets.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.8')),

-- A.9 Access Control
('A.9.1.1', 'Access control policy', 'An access control policy shall be established, documented and reviewed based on business and information security requirements.', 'Asset owners should determine appropriate access control rules, access rights and restrictions for specific user roles towards their assets.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.9')),
('A.9.1.2', 'Access to networks and network services', 'Users shall only be provided with access to the network and network services that they have been specifically authorized to use.', 'A policy should be formulated concerning the use of networks and network services.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.9')),
('A.9.2.1', 'User registration and de-registration', 'A formal user registration and de-registration process shall be implemented to enable assignment of access rights.', 'A formal user registration and de-registration procedure should be implemented for granting and revoking access to all information systems and services.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.9')),
('A.9.2.2', 'User access provisioning', 'A formal user access provisioning process shall be implemented to assign or revoke access rights for all user types to all systems and services.', 'A formal user access provisioning process should be implemented to assign or revoke access rights.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.9')),
('A.9.2.3', 'Management of privileged access rights', 'The allocation and use of privileged access rights shall be restricted and controlled.', 'The allocation of privileged access rights should be controlled through a formal authorization process.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.9')),

-- A.10 Cryptography
('A.10.1.1', 'Policy on the use of cryptographic controls', 'A policy on the use of cryptographic controls for protection of information shall be developed and implemented.', 'A policy should be developed on the use of cryptographic controls including key management.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.10')),
('A.10.1.2', 'Key management', 'A policy on the use, protection and lifetime of cryptographic keys shall be developed and implemented through their whole lifecycle.', 'All aspects of key management should be addressed including the generation, storage, archiving, retrieval, distribution, retirement and destruction of cryptographic keys.', (SELECT id FROM iso27002_control_categories WHERE category_code = 'A.10'))

ON CONFLICT (control_code) DO NOTHING;
