-- Seed comprehensive third party risk evaluation questions
-- Based on industry best practices and regulatory frameworks

INSERT INTO third_party_risk_questions (question_id, category, subcategory, question_text, question_type, response_options, weight, compliance_frameworks, best_practice_guidance, risk_impact_description, sort_order) VALUES

-- Security & Data Protection Category
('SEC-001', 'Security & Data Protection', 'Information Security Management', 'Does the vendor have a formal Information Security Management System (ISMS) in place?', 'Multiple Choice', '["Yes, certified (ISO 27001)", "Yes, but not certified", "In development", "No"]', 1.0, ARRAY['ISO27001', 'SOC2'], 'Vendors should have a comprehensive ISMS with documented policies, procedures, and controls. ISO 27001 certification provides third-party validation.', 'Lack of formal ISMS increases risk of security incidents, data breaches, and compliance violations.', 1),

('SEC-002', 'Security & Data Protection', 'Access Control', 'How does the vendor manage user access to systems and data?', 'Multiple Choice', '["Role-based access control with regular reviews", "Basic access control with periodic reviews", "Manual access management", "No formal access control"]', 1.0, ARRAY['ISO27001', 'SOC2', 'NIST'], 'Implement principle of least privilege, regular access reviews, and automated provisioning/deprovisioning processes.', 'Poor access control can lead to unauthorized access, data breaches, and insider threats.', 2),

('SEC-003', 'Security & Data Protection', 'Data Encryption', 'What encryption standards does the vendor use for data at rest and in transit?', 'Multiple Choice', '["AES-256 for rest, TLS 1.3 for transit", "AES-128 for rest, TLS 1.2 for transit", "Basic encryption implemented", "No encryption or unclear standards"]', 1.0, ARRAY['GDPR', 'SOC2', 'PCI-DSS'], 'Use industry-standard encryption (AES-256, TLS 1.3) with proper key management practices.', 'Weak or missing encryption exposes sensitive data to unauthorized access and regulatory penalties.', 3),

('SEC-004', 'Security & Data Protection', 'Vulnerability Management', 'How frequently does the vendor conduct vulnerability assessments and penetration testing?', 'Multiple Choice', '["Quarterly assessments, annual penetration testing", "Semi-annual assessments", "Annual assessments only", "Ad-hoc or no formal testing"]', 0.8, ARRAY['ISO27001', 'SOC2'], 'Regular vulnerability assessments (quarterly) and annual penetration testing by qualified third parties.', 'Inadequate vulnerability management increases exposure to cyber attacks and system compromises.', 4),

('SEC-005', 'Security & Data Protection', 'Incident Response', 'Does the vendor have a documented incident response plan with defined notification procedures?', 'Multiple Choice', '["Yes, tested and regularly updated", "Yes, but not regularly tested", "Basic plan exists", "No formal incident response plan"]', 1.0, ARRAY['ISO27001', 'SOC2', 'GDPR'], 'Maintain tested incident response plan with clear roles, communication procedures, and notification timelines.', 'Poor incident response can amplify security breaches and delay recovery efforts.', 5),

-- Privacy & Data Handling Category
('PRI-001', 'Privacy & Data Handling', 'Data Classification', 'How does the vendor classify and handle different types of data?', 'Multiple Choice', '["Comprehensive data classification with handling procedures", "Basic data classification", "Informal data handling", "No data classification"]', 1.0, ARRAY['GDPR', 'CCPA', 'ISO27001'], 'Implement comprehensive data classification scheme with appropriate handling, storage, and disposal procedures.', 'Poor data classification can lead to inappropriate handling of sensitive information and privacy violations.', 6),

('PRI-002', 'Privacy & Data Handling', 'Data Retention', 'What are the vendor\'s data retention and disposal policies?', 'Multiple Choice', '["Documented policies with automated enforcement", "Documented policies, manual enforcement", "Basic retention guidelines", "No formal retention policies"]', 0.9, ARRAY['GDPR', 'CCPA', 'HIPAA'], 'Establish clear data retention schedules with secure disposal methods and audit trails.', 'Inadequate data retention practices can lead to regulatory violations and increased data exposure.', 7),

('PRI-003', 'Privacy & Data Handling', 'Cross-Border Data Transfer', 'How does the vendor handle cross-border data transfers?', 'Multiple Choice', '["Adequate safeguards with legal mechanisms", "Basic cross-border controls", "Limited cross-border activity", "No specific cross-border controls"]', 1.0, ARRAY['GDPR', 'CCPA'], 'Implement appropriate safeguards for international data transfers including adequacy decisions or standard contractual clauses.', 'Improper cross-border transfers can result in regulatory violations and data protection breaches.', 8),

('PRI-004', 'Privacy & Data Handling', 'Data Subject Rights', 'Can the vendor support data subject rights requests (access, rectification, erasure)?', 'Multiple Choice', '["Automated systems with defined SLAs", "Manual processes with documented procedures", "Basic capability", "Limited or no capability"]', 0.8, ARRAY['GDPR', 'CCPA'], 'Implement systems and processes to handle data subject requests within regulatory timeframes.', 'Inability to support data subject rights can lead to regulatory penalties and reputational damage.', 9),

-- Operational Risk Category
('OPR-001', 'Operational Risk', 'Business Continuity', 'Does the vendor have a tested business continuity and disaster recovery plan?', 'Multiple Choice', '["Comprehensive plan, regularly tested", "Plan exists, periodic testing", "Basic plan, limited testing", "No formal BCP/DR plan"]', 1.0, ARRAY['ISO22301', 'SOC2'], 'Maintain comprehensive BCP/DR plans with regular testing and defined recovery objectives (RTO/RPO).', 'Inadequate business continuity planning can result in service disruptions and operational failures.', 10),

('OPR-002', 'Operational Risk', 'Change Management', 'How does the vendor manage changes to systems and processes?', 'Multiple Choice', '["Formal change management with approval workflows", "Basic change control processes", "Informal change management", "No formal change management"]', 0.8, ARRAY['ISO27001', 'SOC2'], 'Implement formal change management processes with proper testing, approval, and rollback procedures.', 'Poor change management can lead to system instability, security vulnerabilities, and service disruptions.', 11),

('OPR-003', 'Operational Risk', 'Capacity Management', 'How does the vendor monitor and manage system capacity and performance?', 'Multiple Choice', '["Proactive monitoring with automated scaling", "Regular monitoring with manual intervention", "Basic monitoring capabilities", "Limited or no capacity monitoring"]', 0.7, ARRAY['SOC2'], 'Implement proactive capacity monitoring with automated alerting and scaling capabilities.', 'Inadequate capacity management can result in performance degradation and service outages.', 12),

('OPR-004', 'Operational Risk', 'Vendor Management', 'How does the vendor manage their own third-party suppliers and subcontractors?', 'Multiple Choice', '["Comprehensive vendor risk management program", "Basic vendor oversight", "Limited vendor management", "No formal vendor management"]', 0.9, ARRAY['ISO27001', 'SOC2'], 'Maintain comprehensive vendor management program with due diligence, monitoring, and contractual controls.', 'Poor vendor management creates cascading risks through the supply chain.', 13),

-- Financial Stability Category
('FIN-001', 'Financial Stability', 'Financial Health', 'What is the vendor\'s current financial stability and credit rating?', 'Multiple Choice', '["Strong financial position, investment grade", "Stable financial position", "Some financial concerns", "Significant financial risks"]', 1.0, ARRAY[], 'Assess vendor financial statements, credit ratings, and market position to ensure long-term viability.', 'Financial instability can lead to service disruptions, contract breaches, and business failure.', 14),

('FIN-002', 'Financial Stability', 'Insurance Coverage', 'Does the vendor maintain adequate insurance coverage including cyber liability?', 'Multiple Choice', '["Comprehensive coverage including cyber liability", "Basic insurance coverage", "Limited insurance coverage", "Inadequate or no insurance"]', 0.8, ARRAY[], 'Require comprehensive insurance including professional liability, errors & omissions, and cyber liability coverage.', 'Inadequate insurance coverage increases financial exposure in case of incidents or failures.', 15),

('FIN-003', 'Financial Stability', 'Service Level Agreements', 'Are there clear SLAs with financial penalties for non-performance?', 'Multiple Choice', '["Comprehensive SLAs with financial penalties", "Basic SLAs with some penalties", "SLAs without penalties", "No formal SLAs"]', 0.7, ARRAY[], 'Establish clear SLAs with measurable metrics and appropriate financial penalties for non-compliance.', 'Weak SLAs provide limited recourse for poor performance and service failures.', 16),

-- Compliance & Regulatory Category
('COM-001', 'Compliance & Regulatory', 'Regulatory Compliance', 'Is the vendor compliant with relevant industry regulations and standards?', 'Multiple Choice', '["Fully compliant with all relevant regulations", "Mostly compliant with minor gaps", "Some compliance gaps identified", "Significant compliance deficiencies"]', 1.0, ARRAY['GDPR', 'HIPAA', 'SOX', 'PCI-DSS'], 'Ensure vendor compliance with all applicable regulations and maintain evidence of compliance.', 'Non-compliance can result in regulatory penalties, legal liability, and reputational damage.', 17),

('COM-002', 'Compliance & Regulatory', 'Audit and Certification', 'What third-party audits and certifications does the vendor maintain?', 'Multiple Choice', '["Multiple relevant certifications (SOC2, ISO27001, etc.)", "Some industry certifications", "Limited certifications", "No third-party certifications"]', 0.9, ARRAY['SOC2', 'ISO27001', 'PCI-DSS'], 'Maintain relevant industry certifications and undergo regular third-party audits.', 'Lack of certifications indicates potential gaps in security and compliance controls.', 18),

('COM-003', 'Compliance & Regulatory', 'Legal and Contractual', 'Are there appropriate legal protections and contractual safeguards in place?', 'Multiple Choice', '["Comprehensive legal protections and indemnification", "Basic contractual protections", "Limited legal safeguards", "Inadequate legal protections"]', 0.8, ARRAY[], 'Ensure comprehensive contractual protections including indemnification, limitation of liability, and termination rights.', 'Weak legal protections increase exposure to liability and limit recourse options.', 19),

-- Business Continuity Category
('BC-001', 'Business Continuity', 'Backup and Recovery', 'What are the vendor\'s backup and recovery capabilities?', 'Multiple Choice', '["Automated backups with tested recovery procedures", "Regular backups with documented recovery", "Basic backup capabilities", "Limited or no backup procedures"]', 1.0, ARRAY['ISO22301', 'SOC2'], 'Implement automated backup systems with regular testing of recovery procedures and defined recovery objectives.', 'Inadequate backup and recovery capabilities can result in permanent data loss and extended outages.', 20),

('BC-002', 'Business Continuity', 'Geographic Redundancy', 'Does the vendor have geographically distributed infrastructure and operations?', 'Multiple Choice', '["Multiple geographic regions with failover", "Some geographic distribution", "Limited geographic redundancy", "Single location dependency"]', 0.8, ARRAY['SOC2'], 'Maintain geographically distributed infrastructure to reduce single points of failure.', 'Geographic concentration increases risk of widespread service disruption from natural disasters or regional events.', 21),

('BC-003', 'Business Continuity', 'Communication Plan', 'Does the vendor have a crisis communication plan for stakeholders?', 'Multiple Choice', '["Comprehensive communication plan with multiple channels", "Basic communication procedures", "Limited communication planning", "No formal communication plan"]', 0.6, ARRAY[], 'Establish clear communication plans with defined roles, channels, and escalation procedures for crisis situations.', 'Poor crisis communication can amplify the impact of incidents and damage stakeholder relationships.', 22);

-- Update sequence values to ensure proper auto-increment
SELECT setval('third_party_risk_questions_id_seq', (SELECT MAX(id) FROM third_party_risk_questions));
