-- Insert sample vulnerability data
INSERT INTO vulnerabilities (
    name,
    description,
    severity,
    cvss_score,
    category,
    affected_systems,
    remediation_status,
    priority,
    external_references,
    tags,
    created_at
) VALUES 
-- Critical Vulnerabilities
(
    'SQL Injection in User Authentication',
    'Critical SQL injection vulnerability in user authentication module allowing unauthorized access to sensitive data',
    'Critical',
    9.8,
    'Injection',
    '["Web Application", "Database Server", "Authentication System"]'::jsonb,
    'Open',
    1,
    '["CWE-89", "OWASP-A03"]'::jsonb,
    '["sql-injection", "authentication", "web-security"]'::jsonb,
    NOW() - INTERVAL '2 days'
),
(
    'Remote Code Execution in File Upload',
    'Unrestricted file upload allowing remote code execution on the server',
    'Critical',
    9.9,
    'Code Execution',
    '["Web Server", "File System"]'::jsonb,
    'In Progress',
    1,
    '["CWE-434", "OWASP-A04"]'::jsonb,
    '["rce", "file-upload", "web-security"]'::jsonb,
    NOW() - INTERVAL '5 days'
),
(
    'Privilege Escalation in Admin Panel',
    'Vertical privilege escalation vulnerability allowing regular users to gain administrative access',
    'Critical',
    8.8,
    'Access Control',
    '["Admin Panel", "User Management System"]'::jsonb,
    'Open',
    1,
    '["CWE-269", "OWASP-A01"]'::jsonb,
    '["privilege-escalation", "access-control"]'::jsonb,
    NOW() - INTERVAL '1 day'
),
(
    'Unpatched Software',
    'Software with known security vulnerabilities that have not been patched',
    'System',
    'Critical',
    9.1,
    null,
    '["Operating systems", "Applications"]'::jsonb,
    'In Progress',
    '["Implement automated patch management system"]'::jsonb,
    '["unpatched-software", "system-vulnerability"]'::jsonb,
    NOW() - INTERVAL '15 days'
),
(
    'Privilege Escalation',
    'Vulnerability that allows users to gain elevated access beyond their authorized level',
    'System',
    'High',
    8.4,
    'CVE-2023-5678',
    '["Operating systems"]'::jsonb,
    'Open',
    '["Review and restrict user privileges, implement least privilege principle"]'::jsonb,
    '["privilege-escalation", "system-vulnerability"]'::jsonb,
    NOW() - INTERVAL '14 days'
),
(
    'Buffer Overflow',
    'Vulnerability where program writes more data to a buffer than it can hold',
    'System',
    'Critical',
    9.3,
    'CVE-2023-6789',
    '["Applications", "System software"]'::jsonb,
    'Resolved',
    '["Updated affected software to patched version"]'::jsonb,
    '["buffer-overflow", "system-vulnerability"]'::jsonb,
    NOW() - INTERVAL '13 days'
),
(
    'Weak Encryption',
    'Use of outdated or weak cryptographic algorithms',
    'Cryptography',
    'Medium',
    6.8,
    null,
    '["Encryption systems"]'::jsonb,
    'In Progress',
    '["Upgrade to stronger encryption algorithms (AES-256, RSA-2048+)"]'::jsonb,
    '["weak-encryption", "cryptography"]'::jsonb,
    NOW() - INTERVAL '12 days'
),

-- High Vulnerabilities
(
    'Cross-Site Scripting (XSS) in Comments',
    'Stored XSS vulnerability in comment system allowing malicious script execution',
    'High',
    7.2,
    'Cross-Site Scripting',
    '["Web Application", "Comment System"]'::jsonb,
    'Resolved',
    2,
    '["CWE-79", "OWASP-A03"]'::jsonb,
    '["xss", "stored-xss", "web-security"]'::jsonb,
    NOW() - INTERVAL '10 days'
),
(
    'Insecure Direct Object Reference',
    'IDOR vulnerability allowing users to access unauthorized resources by manipulating object references',
    'High',
    6.5,
    'Access Control',
    '["API Endpoints", "User Data"]'::jsonb,
    'In Progress',
    2,
    '["CWE-639", "OWASP-A01"]'::jsonb,
    '["idor", "access-control", "api-security"]'::jsonb,
    NOW() - INTERVAL '7 days'
),
(
    'Weak Password Policy',
    'Insufficient password complexity requirements allowing weak passwords',
    'High',
    6.1,
    'Authentication',
    '["Authentication System", "User Accounts"]'::jsonb,
    'Open',
    2,
    '["CWE-521", "OWASP-A07"]'::jsonb,
    '["password-policy", "authentication"]'::jsonb,
    NOW() - INTERVAL '3 days'
),
(
    'Unencrypted Communications',
    'Data transmitted without encryption can be intercepted and read by attackers',
    'Network',
    'High',
    7.4,
    null,
    '["Network communications"]'::jsonb,
    'Open',
    '["Implement TLS/SSL encryption for all communications"]'::jsonb,
    '["unencrypted-communications", "network-vulnerability"]'::jsonb,
    NOW() - INTERVAL '9 days'
),
(
    'Weak Authentication',
    'Systems using weak or default credentials that can be easily compromised',
    'Authentication',
    'High',
    8.8,
    null,
    '["Authentication systems"]'::jsonb,
    'In Progress',
    '["Implement strong password policies and multi-factor authentication"]'::jsonb,
    '["weak-authentication", "authentication-vulnerability"]'::jsonb,
    NOW() - INTERVAL '8 days'
),
(
    'Open Ports and Services',
    'Unnecessary network services running that increase attack surface',
    'Network',
    'Medium',
    5.9,
    null,
    '["Network infrastructure"]'::jsonb,
    'Resolved',
    '["Disabled unnecessary services and closed unused ports"]'::jsonb,
    '["open-ports-services", "network-vulnerability"]'::jsonb,
    NOW() - INTERVAL '11 days'
),
(
    'DNS Spoofing',
    'Attack where DNS queries are redirected to malicious servers',
    'Network',
    'Medium',
    6.5,
    'CVE-2023-4567',
    '["DNS servers"]'::jsonb,
    'Open',
    '["Implement DNS security extensions (DNSSEC)"]'::jsonb,
    '["dns-spoofing", "network-vulnerability"]'::jsonb,
    NOW() - INTERVAL '10 days'
),
(
    'Insecure Data Storage',
    'Sensitive data stored without proper protection on mobile devices',
    'Mobile',
    'High',
    7.2,
    null,
    '["Mobile applications"]'::jsonb,
    'Open',
    '["Implement secure storage mechanisms and data encryption"]'::jsonb,
    '["insecure-data-storage", "mobile-vulnerability"]'::jsonb,
    NOW() - INTERVAL '13 days'
),
(
    'Insecure Communication',
    'Mobile apps communicating over insecure channels',
    'Mobile',
    'High',
    7.8,
    null,
    '["Mobile applications"]'::jsonb,
    'In Progress',
    '["Implement certificate pinning and secure communication protocols"]'::jsonb,
    '["insecure-communication", "mobile-vulnerability"]'::jsonb,
    NOW() - INTERVAL '12 days'
),
(
    'Default IoT Credentials',
    'IoT devices using default or weak credentials',
    'IoT',
    'Critical',
    9.0,
    'CVE-2023-7890',
    '["IoT devices"]'::jsonb,
    'Open',
    '["Change default credentials and implement strong authentication"]'::jsonb,
    '["default-iot-credentials", "iot-vulnerability"]'::jsonb,
    NOW() - INTERVAL '14 days'
),
(
    'Firmware Vulnerabilities',
    'Security flaws in device firmware that can be exploited',
    'IoT',
    'High',
    8.2,
    'CVE-2023-8901',
    '["IoT devices", "Embedded systems"]'::jsonb,
    'In Progress',
    '["Update firmware to latest versions"]'::jsonb,
    '["firmware-vulnerabilities", "iot-vulnerability"]'::jsonb,
    NOW() - INTERVAL '13 days'
),
(
    'Misconfigured Cloud Storage',
    'Cloud storage buckets or containers with improper access controls',
    'Cloud',
    'High',
    8.6,
    null,
    '["Cloud storage services"]'::jsonb,
    'Resolved',
    '["Implemented proper access controls and monitoring"]'::jsonb,
    '["misconfigured-cloud-storage", "cloud-vulnerability"]'::jsonb,
    NOW() - INTERVAL '15 days'
),
(
    'Insecure APIs',
    'APIs with insufficient authentication, authorization, or input validation',
    'API',
    'High',
    7.9,
    null,
    '["API endpoints"]'::jsonb,
    'In Progress',
    '["Implement API security best practices and rate limiting"]'::jsonb,
    '["insecure-apis", "api-vulnerability"]'::jsonb,
    NOW() - INTERVAL '14 days'
),
(
    'Container Vulnerabilities',
    'Security flaws in container images or runtime configurations',
    'Container',
    'Medium',
    6.3,
    'CVE-2023-9012',
    '["Container platforms"]'::jsonb,
    'Open',
    '["Scan container images and implement security policies"]'::jsonb,
    '["container-vulnerabilities", "container-vulnerability"]'::jsonb,
    NOW() - INTERVAL '13 days'
),
(
    'Serverless Security Issues',
    'Security misconfigurations in serverless function deployments',
    'Cloud',
    'Medium',
    5.7,
    null,
    '["Serverless functions"]'::jsonb,
    'In Progress',
    '["Review function permissions and implement proper logging"]'::jsonb,
    '["serverless-security-issues", "cloud-vulnerability"]'::jsonb,
    NOW() - INTERVAL '12 days'
),
(
    'Phishing Attacks',
    'Attempts to obtain sensitive information through deceptive communications',
    'Social Engineering',
    'High',
    7.1,
    null,
    '["Email systems", "Users"]'::jsonb,
    'In Progress',
    '["Implement email security and user awareness training"]'::jsonb,
    '["phishing-attacks", "social-engineering"]'::jsonb,
    NOW() - INTERVAL '11 days'
),
(
    'Physical Security Breach',
    'Unauthorized physical access to systems or facilities',
    'Physical',
    'Medium',
    6.0,
    null,
    '["Physical infrastructure"]'::jsonb,
    'Open',
    '["Enhance physical access controls and monitoring"]'::jsonb,
    '["physical-security-breach", "physical-vulnerability"]'::jsonb,
    NOW() - INTERVAL '10 days'
),
(
    'USB/Removable Media Attacks',
    'Malware spread through infected removable media',
    'Physical',
    'Medium',
    6.4,
    null,
    '["Workstations", "Servers"]'::jsonb,
    'Resolved',
    '["Disabled autorun and implemented endpoint protection"]'::jsonb,
    '["usb-removable-media-attacks", "physical-vulnerability"]'::jsonb,
    NOW() - INTERVAL '9 days'
),
(
    'Data Leakage',
    'Unintentional exposure of sensitive data',
    'Data Protection',
    'High',
    8.0,
    null,
    '["Data storage systems"]'::jsonb,
    'In Progress',
    '["Implement data loss prevention (DLP) solutions"]'::jsonb,
    '["data-leakage", "data-protection"]'::jsonb,
    NOW() - INTERVAL '8 days'
),
(
    'Inadequate Logging',
    'Insufficient logging and monitoring of security events',
    'Monitoring',
    'Medium',
    5.1,
    null,
    '["Logging systems"]'::jsonb,
    'Open',
    '["Enhance logging capabilities and implement SIEM"]'::jsonb,
    '["inadequate-logging", "monitoring"]'::jsonb,
    NOW() - INTERVAL '7 days'
),
(
    'Backup Security Issues',
    'Insecure backup storage or inadequate backup procedures',
    'Data Protection',
    'Medium',
    6.2,
    null,
    '["Backup systems"]'::jsonb,
    'In Progress',
    '["Encrypt backups and test restoration procedures"]'::jsonb,
    '["backup-security-issues", "data-protection"]'::jsonb,
    NOW() - INTERVAL '6 days'
),
(
    'Third-Party Component Vulnerabilities',
    'Security flaws in third-party libraries or components',
    'Supply Chain',
    'High',
    7.6,
    'CVE-2023-0123',
    '["Applications using third-party components"]'::jsonb,
    'Open',
    '["Implement software composition analysis and update vulnerable components"]'::jsonb,
    '["third-party-component-vulnerabilities", "supply-chain"]'::jsonb,
    NOW() - INTERVAL '5 days'
),
(
    'Vendor Security Issues',
    'Security risks from third-party vendors and suppliers',
    'Supply Chain',
    'Medium',
    5.8,
    null,
    '["Third-party services"]'::jsonb,
    'In Progress',
    '["Conduct vendor security assessments and implement contracts with security requirements"]'::jsonb,
    '["vendor-security-issues", "supply-chain"]'::jsonb,
    NOW() - INTERVAL '4 days'
),

-- Medium Vulnerabilities
(
    'Missing Security Headers',
    'Web application missing critical security headers (CSP, HSTS, X-Frame-Options)',
    'Configuration',
    5.3,
    'Configuration',
    '["Web Server", "HTTP Headers"]'::jsonb,
    'Open',
    3,
    '["OWASP-A05"]'::jsonb,
    '["security-headers", "configuration"]'::jsonb,
    NOW() - INTERVAL '6 days'
),
(
    'Unencrypted Data Transmission',
    'Sensitive data transmitted over unencrypted HTTP connections',
    'Medium',
    5.9,
    'Cryptography',
    '["Network Communication", "Data Transmission"]'::jsonb,
    'In Progress',
    3,
    '["CWE-319", "OWASP-A02"]'::jsonb,
    '["encryption", "data-transmission"]'::jsonb,
    NOW() - INTERVAL '8 days'
),
(
    'Session Fixation Vulnerability',
    'Application vulnerable to session fixation attacks',
    'Medium',
    5.4,
    'Session Management',
    '["Session Management", "Authentication"]'::jsonb,
    'Open',
    3,
    '["CWE-384", "OWASP-A07"]'::jsonb,
    '["session-fixation", "session-management"]'::jsonb,
    NOW() - INTERVAL '4 days'
),

-- Low Vulnerabilities
(
    'Information Disclosure in Error Messages',
    'Detailed error messages revealing sensitive system information',
    'Low',
    3.7,
    'Information Disclosure',
    '["Error Handling", "System Information"]'::jsonb,
    'Accepted Risk',
    4,
    '["CWE-209", "OWASP-A09"]'::jsonb,
    '["information-disclosure", "error-handling"]'::jsonb,
    NOW() - INTERVAL '12 days'
),
(
    'Missing Rate Limiting',
    'API endpoints lack proper rate limiting controls',
    'Low',
    3.1,
    'Rate Limiting',
    '["API Endpoints", "Rate Limiting"]'::jsonb,
    'Open',
    4,
    '["CWE-770", "OWASP-A04"]'::jsonb,
    '["rate-limiting", "api-security"]'::jsonb,
    NOW() - INTERVAL '9 days'
),
(
    'Outdated Software Components',
    'Application uses outdated third-party components with known vulnerabilities',
    'Low',
    4.0,
    'Component Security',
    '["Third-party Libraries", "Dependencies"]'::jsonb,
    'In Progress',
    4,
    '["OWASP-A06"]'::jsonb,
    '["outdated-components", "dependencies"]'::jsonb,
    NOW() - INTERVAL '15 days'
),

-- Additional vulnerabilities for better search testing
(
    'Buffer Overflow in Legacy System',
    'Stack-based buffer overflow in legacy C application',
    'High',
    7.8,
    'Memory Corruption',
    '["Legacy Application", "Memory Management"]'::jsonb,
    'Open',
    2,
    '["CWE-121"]'::jsonb,
    '["buffer-overflow", "memory-corruption", "legacy"]'::jsonb,
    NOW() - INTERVAL '6 days'
),
(
    'XML External Entity (XXE) Injection',
    'XXE vulnerability in XML parser allowing file disclosure and SSRF',
    'High',
    7.5,
    'Injection',
    '["XML Parser", "File System"]'::jsonb,
    'Resolved',
    2,
    '["CWE-611", "OWASP-A03"]'::jsonb,
    '["xxe", "xml-injection", "ssrf"]'::jsonb,
    NOW() - INTERVAL '20 days'
),
(
    'Insecure Cryptographic Storage',
    'Sensitive data stored using weak encryption algorithms',
    'Medium',
    5.7,
    'Cryptography',
    '["Database", "Encryption"]'::jsonb,
    'Open',
    3,
    '["CWE-327", "OWASP-A02"]'::jsonb,
    '["weak-encryption", "cryptography", "data-storage"]'::jsonb,
    NOW() - INTERVAL '11 days'
),
(
    'Cross-Site Request Forgery (CSRF)',
    'CSRF vulnerability in state-changing operations',
    'Medium',
    4.3,
    'Cross-Site Request Forgery',
    '["Web Application", "State Management"]'::jsonb,
    'In Progress',
    3,
    '["CWE-352", "OWASP-A01"]'::jsonb,
    '["csrf", "web-security"]'::jsonb,
    NOW() - INTERVAL '5 days'
);

-- Update statistics
ANALYZE vulnerabilities;
