-- Insert 20 sample records into iso27001_risks table
-- Based on the schema from scripts/40-create-iso27001-risks-table.sql

INSERT INTO iso27001_risks (
    risk_id, 
    title, 
    description, 
    category, 
    likelihood, 
    impact, 
    status, 
    owner, 
    treatment_plan, 
    residual_risk, 
    next_review, 
    controls, 
    assets
) VALUES 
(
    'ISO-R-001',
    'Unauthorized Physical Access to Data Center',
    'Risk of unauthorized personnel gaining physical access to critical IT infrastructure and servers in the data center, potentially leading to data theft, system tampering, or service disruption.',
    'Physical Security',
    2,
    5,
    'Open',
    'Facilities Manager',
    'Implement biometric access controls, security cameras, and 24/7 security personnel. Conduct regular access audits and maintain visitor logs.',
    4,
    '2024-06-15',
    ARRAY['A.11.1.1', 'A.11.1.2', 'A.11.2.1'],
    ARRAY['Data Center', 'Server Infrastructure', 'Network Equipment']
),
(
    'ISO-R-002',
    'Malware Infection Through Email Attachments',
    'Risk of malware infection spreading through the organization via malicious email attachments, potentially compromising systems and data integrity.',
    'Malware Protection',
    4,
    4,
    'In Progress',
    'IT Security Team',
    'Deploy advanced email security gateway, implement endpoint detection and response (EDR), and conduct regular security awareness training.',
    8,
    '2024-05-30',
    ARRAY['A.12.2.1', 'A.13.2.1', 'A.7.2.2'],
    ARRAY['Email System', 'User Workstations', 'File Servers']
),
(
    'ISO-R-003',
    'Insider Threat - Privileged User Abuse',
    'Risk of privileged users misusing their access rights to steal sensitive data, modify critical systems, or cause operational disruption.',
    'Insider Threats',
    2,
    5,
    'Open',
    'CISO',
    'Implement privileged access management (PAM), user behavior analytics, and regular access reviews. Establish separation of duties for critical operations.',
    6,
    '2024-07-01',
    ARRAY['A.9.2.3', 'A.9.2.5', 'A.12.4.1'],
    ARRAY['Administrative Systems', 'Database Systems', 'Critical Applications']
),
(
    'ISO-R-004',
    'Cloud Data Breach Due to Misconfiguration',
    'Risk of sensitive data exposure in cloud environments due to misconfigured security settings, inadequate access controls, or unsecured storage buckets.',
    'Cloud Security',
    3,
    4,
    'Open',
    'Cloud Architect',
    'Implement cloud security posture management (CSPM), automated configuration scanning, and cloud access security broker (CASB) solutions.',
    6,
    '2024-06-20',
    ARRAY['A.13.1.1', 'A.14.1.3', 'A.15.1.2'],
    ARRAY['Cloud Storage', 'Cloud Applications', 'API Gateway']
),
(
    'ISO-R-005',
    'Network Intrusion via Unpatched Vulnerabilities',
    'Risk of network compromise through exploitation of unpatched vulnerabilities in network devices, servers, and applications.',
    'Vulnerability Management',
    3,
    4,
    'In Progress',
    'Network Administrator',
    'Establish automated patch management system, conduct regular vulnerability assessments, and implement network segmentation.',
    6,
    '2024-06-10',
    ARRAY['A.12.6.1', 'A.13.1.1', 'A.14.2.3'],
    ARRAY['Network Infrastructure', 'Servers', 'Applications']
),
(
    'ISO-R-006',
    'Data Loss Through Portable Media',
    'Risk of sensitive data loss or theft through unauthorized use of USB drives, external hard drives, and other portable storage devices.',
    'Data Loss Prevention',
    3,
    3,
    'Mitigated',
    'Data Protection Officer',
    'Implement endpoint DLP solutions, disable USB ports on critical systems, and encrypt all portable media usage.',
    2,
    '2024-08-15',
    ARRAY['A.8.3.1', 'A.10.1.1', 'A.13.2.3'],
    ARRAY['Workstations', 'Portable Devices', 'Sensitive Data']
),
(
    'ISO-R-007',
    'Social Engineering Attack on Help Desk',
    'Risk of unauthorized access to systems and data through social engineering attacks targeting help desk personnel to reset passwords or provide system access.',
    'Social Engineering',
    4,
    3,
    'Open',
    'Help Desk Manager',
    'Implement strict identity verification procedures, provide social engineering awareness training, and establish callback verification protocols.',
    8,
    '2024-05-25',
    ARRAY['A.7.2.2', 'A.9.2.1', 'A.13.2.1'],
    ARRAY['Help Desk Systems', 'User Accounts', 'Identity Management']
),
(
    'ISO-R-008',
    'Database SQL Injection Attack',
    'Risk of database compromise and data theft through SQL injection vulnerabilities in web applications that interact with backend databases.',
    'Application Security',
    3,
    5,
    'Open',
    'Application Security Lead',
    'Implement input validation, parameterized queries, web application firewall (WAF), and regular security code reviews.',
    9,
    '2024-06-05',
    ARRAY['A.14.2.1', 'A.14.2.5', 'A.13.1.3'],
    ARRAY['Web Applications', 'Database Systems', 'Customer Data']
),
(
    'ISO-R-009',
    'Ransomware Attack on Critical Systems',
    'Risk of ransomware infection encrypting critical business systems and data, leading to operational shutdown and potential data loss.',
    'Ransomware',
    3,
    5,
    'In Progress',
    'Incident Response Team',
    'Implement endpoint protection, network segmentation, offline backups, and incident response procedures. Conduct regular backup testing.',
    9,
    '2024-05-20',
    ARRAY['A.12.2.1', 'A.12.3.1', 'A.16.1.1'],
    ARRAY['File Servers', 'Database Systems', 'Backup Systems']
),
(
    'ISO-R-010',
    'Third-Party Vendor Data Breach',
    'Risk of data breach through third-party vendors who have access to organizational systems or process sensitive data on behalf of the organization.',
    'Third-Party Risk',
    2,
    4,
    'Open',
    'Vendor Risk Manager',
    'Conduct thorough vendor security assessments, implement contractual security requirements, and establish ongoing monitoring of vendor security posture.',
    4,
    '2024-07-10',
    ARRAY['A.15.1.1', 'A.15.2.1', 'A.15.2.2'],
    ARRAY['Vendor Systems', 'Shared Data', 'Integration Points']
),
(
    'ISO-R-011',
    'Mobile Device Management Failure',
    'Risk of data exposure and unauthorized access due to inadequate mobile device management, including lost or stolen devices containing corporate data.',
    'Mobile Security',
    4,
    3,
    'Open',
    'Mobile Security Administrator',
    'Implement comprehensive MDM solution, enforce device encryption, enable remote wipe capabilities, and establish BYOD policies.',
    8,
    '2024-06-25',
    ARRAY['A.6.2.1', 'A.10.1.1', 'A.13.2.1'],
    ARRAY['Mobile Devices', 'Corporate Email', 'Business Applications']
),
(
    'ISO-R-012',
    'Weak Authentication Mechanisms',
    'Risk of unauthorized system access due to weak authentication mechanisms, including weak passwords, lack of multi-factor authentication, and inadequate account lockout policies.',
    'Authentication',
    4,
    4,
    'In Progress',
    'Identity and Access Manager',
    'Implement multi-factor authentication, enforce strong password policies, deploy single sign-on (SSO), and conduct regular access reviews.',
    8,
    '2024-06-01',
    ARRAY['A.9.4.2', 'A.9.4.3', 'A.9.2.1'],
    ARRAY['All Systems', 'User Accounts', 'Authentication Infrastructure']
),
(
    'ISO-R-013',
    'Backup System Compromise',
    'Risk of data loss and inability to recover from incidents due to backup system failures, corruption, or compromise by attackers.',
    'Backup and Recovery',
    2,
    5,
    'Open',
    'Backup Administrator',
    'Implement 3-2-1 backup strategy, test backup integrity regularly, secure backup systems with separate credentials, and maintain offline backups.',
    5,
    '2024-07-20',
    ARRAY['A.12.3.1', 'A.17.1.2', 'A.17.1.3'],
    ARRAY['Backup Infrastructure', 'Critical Data', 'Recovery Systems']
),
(
    'ISO-R-014',
    'API Security Vulnerabilities',
    'Risk of data breach and system compromise through insecure application programming interfaces (APIs) that lack proper authentication, authorization, and input validation.',
    'API Security',
    3,
    4,
    'Open',
    'API Security Team',
    'Implement API gateway with authentication and rate limiting, conduct API security testing, and establish API security standards.',
    6,
    '2024-06-30',
    ARRAY['A.14.2.1', 'A.13.1.1', 'A.9.4.1'],
    ARRAY['API Gateway', 'Web Services', 'Integration Layer']
),
(
    'ISO-R-015',
    'Remote Access VPN Vulnerabilities',
    'Risk of network compromise through vulnerabilities in VPN infrastructure used for remote access, including weak encryption and authentication bypass.',
    'Remote Access',
    3,
    4,
    'Open',
    'Network Security Team',
    'Update VPN infrastructure, implement certificate-based authentication, enable VPN monitoring, and establish remote access policies.',
    6,
    '2024-06-12',
    ARRAY['A.13.2.1', 'A.6.2.1', 'A.11.2.6'],
    ARRAY['VPN Infrastructure', 'Remote Devices', 'Network Access']
),
(
    'ISO-R-016',
    'IoT Device Security Gaps',
    'Risk of network compromise through insecure Internet of Things (IoT) devices that lack proper security controls and may serve as entry points for attackers.',
    'IoT Security',
    3,
    3,
    'Open',
    'IoT Security Specialist',
    'Implement IoT device inventory, network segmentation for IoT devices, regular firmware updates, and IoT security monitoring.',
    5,
    '2024-07-05',
    ARRAY['A.13.1.1', 'A.11.2.6', 'A.12.6.1'],
    ARRAY['IoT Devices', 'Network Infrastructure', 'Monitoring Systems']
),
(
    'ISO-R-017',
    'Email System Business Email Compromise',
    'Risk of financial fraud and data theft through business email compromise (BEC) attacks targeting executive communications and financial transactions.',
    'Email Security',
    3,
    4,
    'In Progress',
    'Email Security Administrator',
    'Implement DMARC, DKIM, and SPF protocols, deploy email security gateway, and provide targeted phishing awareness training.',
    6,
    '2024-05-28',
    ARRAY['A.13.2.1', 'A.7.2.2', 'A.12.2.1'],
    ARRAY['Email Infrastructure', 'Financial Systems', 'Executive Communications']
),
(
    'ISO-R-018',
    'Configuration Drift and Unauthorized Changes',
    'Risk of security vulnerabilities and system instability due to unauthorized configuration changes and configuration drift from security baselines.',
    'Configuration Management',
    3,
    3,
    'Open',
    'Configuration Manager',
    'Implement configuration management tools, establish change control procedures, and conduct regular configuration audits.',
    5,
    '2024-07-15',
    ARRAY['A.12.1.2', 'A.12.6.2', 'A.14.2.2'],
    ARRAY['System Configurations', 'Infrastructure', 'Security Baselines']
),
(
    'ISO-R-019',
    'Shadow IT and Unauthorized Cloud Services',
    'Risk of data exposure and security gaps due to employees using unauthorized cloud services and applications that bypass corporate security controls.',
    'Shadow IT',
    4,
    3,
    'Open',
    'Cloud Governance Team',
    'Implement cloud access security broker (CASB), establish cloud usage policies, and provide approved alternatives to common shadow IT services.',
    8,
    '2024-06-18',
    ARRAY['A.6.1.3', 'A.15.1.1', 'A.13.2.1'],
    ARRAY['Cloud Services', 'Corporate Data', 'User Devices']
),
(
    'ISO-R-020',
    'Certificate and Key Management Failures',
    'Risk of service disruption and security vulnerabilities due to expired certificates, weak key management practices, and inadequate PKI infrastructure.',
    'Cryptographic Controls',
    2,
    3,
    'Mitigated',
    'PKI Administrator',
    'Implement automated certificate lifecycle management, establish key management procedures, and deploy certificate monitoring tools.',
    2,
    '2024-08-30',
    ARRAY['A.10.1.2', 'A.14.1.3', 'A.12.3.2'],
    ARRAY['SSL Certificates', 'Encryption Keys', 'PKI Infrastructure']
);
