-- Insert 20 comprehensive NIST CSF risk templates
INSERT INTO nist_csf_risk_templates (
    template_id,
    template_name,
    risk_description,
    nist_function,
    nist_category,
    threat_sources,
    vulnerabilities,
    asset_types,
    likelihood_score,
    impact_score,
    risk_level,
    nist_references
) VALUES 
-- GOVERN Function Templates (4)
('GV-001', 'Governance Structure Risk', 
 'Risk of inadequate cybersecurity governance structure leading to poor decision-making and resource allocation',
 'Govern', 'GV.OC', 
 ARRAY['Internal threats', 'Management oversight'], 
 ARRAY['Lack of clear roles', 'Insufficient oversight', 'Poor communication'],
 ARRAY['Organizational processes', 'Management systems'],
 3, 4, 'Medium',
 ARRAY['GV.OC-01', 'GV.OC-02']),

('GV-002', 'Risk Management Strategy Risk',
 'Risk of inadequate risk management strategy failing to address cybersecurity risks effectively',
 'Govern', 'GV.RM',
 ARRAY['Strategic threats', 'Compliance failures'],
 ARRAY['Incomplete risk assessment', 'Outdated policies', 'Lack of integration'],
 ARRAY['Risk management processes', 'Strategic plans'],
 4, 4, 'High',
 ARRAY['GV.RM-01', 'GV.RM-02', 'GV.RM-03']),

('GV-003', 'Roles and Responsibilities Risk',
 'Risk of unclear cybersecurity roles and responsibilities leading to gaps in security coverage',
 'Govern', 'GV.PO',
 ARRAY['Internal threats', 'Human error'],
 ARRAY['Role ambiguity', 'Skill gaps', 'Accountability issues'],
 ARRAY['Personnel', 'Organizational structure'],
 3, 3, 'Medium',
 ARRAY['GV.PO-01', 'GV.PO-02']),

('GV-004', 'Supply Chain Risk Management',
 'Risk of inadequate supply chain cybersecurity risk management affecting organizational security',
 'Govern', 'GV.SC',
 ARRAY['Third-party threats', 'Supply chain attacks'],
 ARRAY['Vendor security gaps', 'Contract weaknesses', 'Monitoring deficiencies'],
 ARRAY['Third-party services', 'Supply chain'],
 4, 5, 'High',
 ARRAY['GV.SC-01', 'GV.SC-02', 'GV.SC-03']),

-- IDENTIFY Function Templates (3)
('ID-001', 'Asset Management Risk',
 'Risk of inadequate asset identification and management leading to security blind spots',
 'Identify', 'ID.AM',
 ARRAY['External attackers', 'Insider threats'],
 ARRAY['Unknown assets', 'Outdated inventory', 'Poor asset classification'],
 ARRAY['Hardware', 'Software', 'Data', 'Systems'],
 4, 4, 'High',
 ARRAY['ID.AM-01', 'ID.AM-02', 'ID.AM-03']),

('ID-002', 'Risk Assessment Process Risk',
 'Risk of inadequate risk assessment processes failing to identify and prioritize cybersecurity risks',
 'Identify', 'ID.RA',
 ARRAY['Various threat actors', 'Environmental factors'],
 ARRAY['Incomplete assessments', 'Outdated methodologies', 'Poor risk prioritization'],
 ARRAY['Risk assessment processes', 'Threat intelligence'],
 3, 4, 'Medium',
 ARRAY['ID.RA-01', 'ID.RA-02', 'ID.RA-03']),

('ID-003', 'Business Environment Understanding Risk',
 'Risk of inadequate understanding of business environment affecting cybersecurity decisions',
 'Identify', 'ID.BE',
 ARRAY['Business disruption', 'Regulatory changes'],
 ARRAY['Poor business context', 'Misaligned priorities', 'Communication gaps'],
 ARRAY['Business processes', 'Stakeholder relationships'],
 3, 3, 'Medium',
 ARRAY['ID.BE-01', 'ID.BE-02', 'ID.BE-03']),

-- PROTECT Function Templates (4)
('PR-001', 'Identity and Access Management Risk',
 'Risk of inadequate identity and access management leading to unauthorized access',
 'Protect', 'PR.AC',
 ARRAY['External attackers', 'Insider threats', 'Credential theft'],
 ARRAY['Weak authentication', 'Excessive privileges', 'Poor access controls'],
 ARRAY['User accounts', 'Systems', 'Applications', 'Data'],
 4, 5, 'High',
 ARRAY['PR.AC-01', 'PR.AC-02', 'PR.AC-03', 'PR.AC-04']),

('PR-002', 'Data Protection Risk',
 'Risk of inadequate data protection measures leading to data breaches and privacy violations',
 'Protect', 'PR.DS',
 ARRAY['Cybercriminals', 'Nation-state actors', 'Insider threats'],
 ARRAY['Weak encryption', 'Poor data handling', 'Inadequate backup'],
 ARRAY['Sensitive data', 'Personal information', 'Intellectual property'],
 4, 5, 'High',
 ARRAY['PR.DS-01', 'PR.DS-02', 'PR.DS-03', 'PR.DS-05']),

('PR-003', 'Security Training Risk',
 'Risk of inadequate security awareness and training leading to human error vulnerabilities',
 'Protect', 'PR.AT',
 ARRAY['Social engineering', 'Phishing attacks', 'Human error'],
 ARRAY['Lack of awareness', 'Insufficient training', 'Poor security culture'],
 ARRAY['Personnel', 'Organizational culture'],
 4, 3, 'Medium',
 ARRAY['PR.AT-01', 'PR.AT-02', 'PR.AT-03']),

('PR-004', 'Protective Technology Risk',
 'Risk of inadequate protective technology implementation failing to prevent cyber attacks',
 'Protect', 'PR.PT',
 ARRAY['Malware', 'Network attacks', 'System exploits'],
 ARRAY['Outdated security tools', 'Misconfiguration', 'Coverage gaps'],
 ARRAY['Security systems', 'Network infrastructure', 'Endpoints'],
 4, 4, 'High',
 ARRAY['PR.PT-01', 'PR.PT-02', 'PR.PT-03', 'PR.PT-04']),

-- DETECT Function Templates (3)
('DE-001', 'Anomaly Detection Risk',
 'Risk of inadequate anomaly detection capabilities failing to identify security incidents',
 'Detect', 'DE.AE',
 ARRAY['Advanced persistent threats', 'Zero-day attacks', 'Insider threats'],
 ARRAY['Poor monitoring', 'Inadequate baselines', 'Alert fatigue'],
 ARRAY['Network traffic', 'System logs', 'User behavior'],
 3, 4, 'Medium',
 ARRAY['DE.AE-01', 'DE.AE-02', 'DE.AE-03']),

('DE-002', 'Security Monitoring Risk',
 'Risk of inadequate security monitoring failing to detect ongoing cyber attacks',
 'Detect', 'DE.CM',
 ARRAY['Persistent attackers', 'Stealth malware', 'Lateral movement'],
 ARRAY['Monitoring gaps', 'Poor log management', 'Insufficient analysis'],
 ARRAY['Security monitoring systems', 'Log data', 'Network segments'],
 4, 4, 'High',
 ARRAY['DE.CM-01', 'DE.CM-02', 'DE.CM-03', 'DE.CM-04']),

('DE-003', 'Detection Process Risk',
 'Risk of inadequate detection processes failing to effectively identify and escalate security events',
 'Detect', 'DE.DP',
 ARRAY['Various threat actors', 'Attack campaigns'],
 ARRAY['Process gaps', 'Poor procedures', 'Inadequate testing'],
 ARRAY['Detection processes', 'Security procedures'],
 3, 3, 'Medium',
 ARRAY['DE.DP-01', 'DE.DP-02', 'DE.DP-03']),

-- RESPOND Function Templates (3)
('RS-001', 'Incident Response Planning Risk',
 'Risk of inadequate incident response planning leading to ineffective incident handling',
 'Respond', 'RS.RP',
 ARRAY['Cyber incidents', 'Security breaches', 'System compromises'],
 ARRAY['Outdated plans', 'Untested procedures', 'Resource constraints'],
 ARRAY['Incident response plans', 'Response team', 'Communication systems'],
 3, 4, 'Medium',
 ARRAY['RS.RP-01', 'RS.RP-02', 'RS.RP-03']),

('RS-002', 'Response Communications Risk',
 'Risk of inadequate response communications affecting incident coordination and stakeholder notification',
 'Respond', 'RS.CO',
 ARRAY['Public relations threats', 'Regulatory scrutiny', 'Stakeholder concerns'],
 ARRAY['Communication gaps', 'Unclear messaging', 'Delayed notifications'],
 ARRAY['Communication channels', 'Stakeholder relationships', 'Public reputation'],
 4, 4, 'High',
 ARRAY['RS.CO-01', 'RS.CO-02', 'RS.CO-03']),

('RS-003', 'Response Analysis Risk',
 'Risk of inadequate incident analysis leading to incomplete understanding and poor decision-making',
 'Respond', 'RS.AN',
 ARRAY['Complex attack scenarios', 'Multi-vector attacks'],
 ARRAY['Analysis gaps', 'Insufficient expertise', 'Time pressures'],
 ARRAY['Forensic data', 'Analysis tools', 'Expert knowledge'],
 3, 3, 'Medium',
 ARRAY['RS.AN-01', 'RS.AN-02', 'RS.AN-03']),

-- RECOVER Function Templates (2)
('RC-001', 'Recovery Planning Risk',
 'Risk of inadequate recovery planning leading to prolonged business disruption',
 'Recover', 'RC.RP',
 ARRAY['Business continuity threats', 'Extended outages'],
 ARRAY['Incomplete plans', 'Untested procedures', 'Resource limitations'],
 ARRAY['Recovery plans', 'Business processes', 'Critical systems'],
 4, 5, 'High',
 ARRAY['RC.RP-01', 'RC.RP-02', 'RC.RP-03']),

('RC-002', 'Recovery Communications Risk',
 'Risk of inadequate recovery communications affecting stakeholder confidence and business relationships',
 'Recover', 'RC.CO',
 ARRAY['Reputation damage', 'Customer loss', 'Regulatory action'],
 ARRAY['Poor communication', 'Inconsistent messaging', 'Delayed updates'],
 ARRAY['Communication systems', 'Stakeholder trust', 'Business reputation'],
 3, 4, 'Medium',
 ARRAY['RC.CO-01', 'RC.CO-02', 'RC.CO-03']);

-- Verify insertion
SELECT 
    nist_function,
    COUNT(*) as template_count
FROM nist_csf_risk_templates 
GROUP BY nist_function 
ORDER BY nist_function;

SELECT 'Successfully inserted 20 NIST CSF risk templates' as status;
