-- Insert Sample HIPAA Requirements for Testing
-- This script populates the hipaa_requirements table with comprehensive HIPAA compliance requirements

-- Administrative Safeguards (§164.308)
INSERT INTO hipaa_requirements (requirement_id, title, description, category, priority, regulation_reference) VALUES
('164.308(a)(1)(i)', 'Security Officer', 'Assign security responsibilities to an individual who is responsible for the development and implementation of the policies and procedures required by this subpart for the entity.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(1)(i)'),
('164.308(a)(1)(ii)(A)', 'Security Management Process', 'Implement policies and procedures to prevent, detect, contain, and correct security violations.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(1)(ii)(A)'),
('164.308(a)(1)(ii)(B)', 'Assigned Security Responsibility', 'Identify the security officer or other person who is assigned security responsibility for the entity.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(1)(ii)(B)'),
('164.308(a)(2)', 'Workforce Training and Access Management', 'Implement policies and procedures to ensure that all members of its workforce have appropriate access to electronic protected health information.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(2)'),
('164.308(a)(3)(i)', 'Information Access Management', 'Implement policies and procedures for authorizing access to electronic protected health information that are consistent with the applicable requirements of subpart E of this part.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(3)(i)'),
('164.308(a)(3)(ii)(A)', 'Isolating Health Care Clearinghouse Functions', 'If a health care clearinghouse is part of a larger organization, the clearinghouse must implement policies and procedures that protect the electronic protected health information of the clearinghouse from unauthorized access by the larger organization.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(3)(ii)(A)'),
('164.308(a)(3)(ii)(B)', 'Access Authorization', 'Implement policies and procedures for granting access to electronic protected health information, for example, through access to a workstation, transaction, program, process, or other mechanism.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(3)(ii)(B)'),
('164.308(a)(3)(ii)(C)', 'Access Establishment and Modification', 'Implement policies and procedures that, based upon the entity''s access authorization policies, establish, document, review, and modify a user''s right of access to a workstation, transaction, program, or process.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(3)(ii)(C)'),
('164.308(a)(4)(i)', 'Security Awareness and Training', 'Implement a security awareness and training program for all members of its workforce (including management).', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(4)(i)'),
('164.308(a)(4)(ii)(A)', 'Security Reminders', 'Periodic security updates.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(4)(ii)(A)'),
('164.308(a)(4)(ii)(B)', 'Protection from Malicious Software', 'Procedures for guarding against, detecting, and reporting malicious software.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(4)(ii)(B)'),
('164.308(a)(4)(ii)(C)', 'Log-in Monitoring', 'Procedures for monitoring log-in attempts and reporting discrepancies.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(4)(ii)(C)'),
('164.308(a)(4)(ii)(D)', 'Password Management', 'Procedures for creating, changing, and safeguarding passwords.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(4)(ii)(D)'),
('164.308(a)(5)(i)', 'Security Incident Procedures', 'Implement policies and procedures to address security incidents.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(5)(i)'),
('164.308(a)(5)(ii)(A)', 'Response and Reporting', 'Identify and respond to suspected or known security incidents; mitigate, to the extent practicable, harmful effects of security incidents that are known to the covered entity or business associate; and document security incidents and their outcomes.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(5)(ii)(A)'),
('164.308(a)(6)(i)', 'Contingency Plan', 'Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(6)(i)'),
('164.308(a)(6)(ii)(A)', 'Data Backup Plan', 'Establish and implement procedures to create and maintain retrievable exact copies of electronic protected health information.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(6)(ii)(A)'),
('164.308(a)(6)(ii)(B)', 'Disaster Recovery Plan', 'Establish (and implement as needed) procedures to restore any loss of data.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(6)(ii)(B)'),
('164.308(a)(6)(ii)(C)', 'Emergency Mode Operation Plan', 'Establish (and implement as needed) procedures to enable continuation of critical business processes for protection of the security of electronic protected health information while operating in emergency mode.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(6)(ii)(C)'),
('164.308(a)(7)(i)', 'Evaluation', 'Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity, and availability of electronic protected health information held by the covered entity or business associate.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(7)(i)'),
('164.308(a)(8)', 'Business Associate Contracts', 'A covered entity may permit a business associate to create, receive, maintain, or transmit electronic protected health information on the covered entity''s behalf only if the covered entity obtains satisfactory assurances that the business associate will appropriately safeguard the information.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(a)(8)'),
('164.308(b)(1)', 'Business Associate Contracts or Other Arrangements', 'The contract or other arrangement between the covered entity and its business associate required by paragraph (a)(8) of this section must meet the requirements of paragraph (b)(2) of this section.', 'Administrative Safeguards', 'Required', '45 CFR 164.308(b)(1)'),
('164.308(b)(3)', 'Written Contract or Other Arrangement', 'Document the satisfactory assurances required by paragraph (a)(8) of this section through a written contract or other arrangement with the business associate that meets the applicable requirements of § 164.314(a).', 'Administrative Safeguards', 'Required', '45 CFR 164.308(b)(3)'),
('164.308(a)(7)(ii)(A)', 'Testing Procedure', 'Implement procedures for periodic testing and revision of contingency plans.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(7)(ii)(A)'),
('164.308(a)(7)(ii)(B)', 'Applications and Data Criticality Analysis', 'Assess the relative criticality of specific applications and data in support of other contingency plan components.', 'Administrative Safeguards', 'Addressable', '45 CFR 164.308(a)(7)(ii)(B)');

-- Physical Safeguards (§164.310)
INSERT INTO hipaa_requirements (requirement_id, title, description, category, priority, regulation_reference) VALUES
('164.310(a)(1)', 'Facility Access Controls', 'Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed.', 'Physical Safeguards', 'Required', '45 CFR 164.310(a)(1)'),
('164.310(a)(2)(i)', 'Contingency Operations', 'Establish (and implement as needed) procedures that allow facility access in support of restoration of lost data under the disaster recovery plan and emergency mode operations plan in the event of an emergency.', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(a)(2)(i)'),
('164.310(a)(2)(ii)', 'Facility Security Plan', 'Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft.', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(a)(2)(ii)'),
('164.310(a)(2)(iii)', 'Access Control and Validation Procedures', 'Implement procedures to control and validate a person''s access to facilities based on their role or function, including visitor control, and control of access to software programs for testing and revision.', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(a)(2)(iii)'),
('164.310(a)(2)(iv)', 'Maintenance Records', 'Implement policies and procedures to document repairs and modifications to the physical components of a facility which are related to security (for example, hardware, walls, doors, and locks).', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(a)(2)(iv)'),
('164.310(b)', 'Workstation Use', 'Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation or class of workstation that can access electronic protected health information.', 'Physical Safeguards', 'Required', '45 CFR 164.310(b)'),
('164.310(c)', 'Workstation Security', 'Implement physical safeguards for all workstations that access electronic protected health information, to restrict access to authorized users.', 'Physical Safeguards', 'Required', '45 CFR 164.310(c)'),
('164.310(d)(1)', 'Device and Media Controls', 'Implement policies and procedures that govern the receipt and removal of hardware and electronic media that contain electronic protected health information into and out of a facility, and the movement of these items within the facility.', 'Physical Safeguards', 'Required', '45 CFR 164.310(d)(1)'),
('164.310(d)(2)(i)', 'Disposal', 'Implement policies and procedures to address the final disposition of electronic protected health information, and/or the hardware or electronic media on which it is stored.', 'Physical Safeguards', 'Required', '45 CFR 164.310(d)(2)(i)'),
('164.310(d)(2)(ii)', 'Media Re-use', 'Implement procedures for removal of electronic protected health information from electronic media before the media are made available for re-use.', 'Physical Safeguards', 'Required', '45 CFR 164.310(d)(2)(ii)'),
('164.310(d)(2)(iii)', 'Accountability', 'Maintain a record of the movements of hardware and electronic media and any person responsible therefore.', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(d)(2)(iii)'),
('164.310(d)(2)(iv)', 'Data Backup and Storage', 'Create a retrievable, exact copy of electronic protected health information, when needed, before movement of equipment.', 'Physical Safeguards', 'Addressable', '45 CFR 164.310(d)(2)(iv)');

-- Technical Safeguards (§164.312)
INSERT INTO hipaa_requirements (requirement_id, title, description, category, priority, regulation_reference) VALUES
('164.312(a)(1)', 'Access Control', 'Implement technical policies and procedures for electronic information systems that maintain electronic protected health information to allow access only to those persons or software programs that have been granted access rights as specified in § 164.308(a)(4).', 'Technical Safeguards', 'Required', '45 CFR 164.312(a)(1)'),
('164.312(a)(2)(i)', 'Unique User Identification', 'Assign a unique name and/or number for identifying and tracking user identity.', 'Technical Safeguards', 'Required', '45 CFR 164.312(a)(2)(i)'),
('164.312(a)(2)(ii)', 'Emergency Access Procedure', 'Establish (and implement as needed) procedures for obtaining necessary electronic protected health information during an emergency.', 'Technical Safeguards', 'Required', '45 CFR 164.312(a)(2)(ii)'),
('164.312(a)(2)(iii)', 'Automatic Logoff', 'Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity.', 'Technical Safeguards', 'Addressable', '45 CFR 164.312(a)(2)(iii)'),
('164.312(a)(2)(iv)', 'Encryption and Decryption', 'Implement a mechanism to encrypt and decrypt electronic protected health information.', 'Technical Safeguards', 'Addressable', '45 CFR 164.312(a)(2)(iv)'),
('164.312(b)', 'Audit Controls', 'Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use electronic protected health information.', 'Technical Safeguards', 'Required', '45 CFR 164.312(b)'),
('164.312(c)(1)', 'Integrity', 'Implement policies and procedures to protect electronic protected health information from improper alteration or destruction.', 'Technical Safeguards', 'Required', '45 CFR 164.312(c)(1)'),
('164.312(c)(2)', 'Mechanism to Authenticate Electronic Protected Health Information', 'Implement electronic mechanisms to corroborate that electronic protected health information has not been altered or destroyed in an unauthorized manner.', 'Technical Safeguards', 'Addressable', '45 CFR 164.312(c)(2)'),
('164.312(d)', 'Person or Entity Authentication', 'Implement procedures to verify that a person or entity seeking access to electronic protected health information is the one claimed.', 'Technical Safeguards', 'Required', '45 CFR 164.312(d)'),
('164.312(e)(1)', 'Transmission Security', 'Implement technical security measures to guard against unauthorized access to electronic protected health information that is being transmitted over an electronic communications network.', 'Technical Safeguards', 'Required', '45 CFR 164.312(e)(1)'),
('164.312(e)(2)(i)', 'Integrity Controls', 'Implement security measures to ensure that electronically transmitted electronic protected health information is not improperly modified without detection until disposed of.', 'Technical Safeguards', 'Addressable', '45 CFR 164.312(e)(2)(i)'),
('164.312(e)(2)(ii)', 'Encryption', 'Implement a mechanism to encrypt electronic protected health information whenever deemed appropriate.', 'Technical Safeguards', 'Addressable', '45 CFR 164.312(e)(2)(ii)');

-- Privacy Rule (§164.502-164.534)
INSERT INTO hipaa_requirements (requirement_id, title, description, category, priority, regulation_reference) VALUES
('164.502(a)', 'Uses and Disclosures of Protected Health Information', 'A covered entity may not use or disclose protected health information, except as permitted or required by this subpart or by subpart C of part 160 of this subchapter.', 'Privacy Rule', 'Required', '45 CFR 164.502(a)'),
('164.502(b)', 'Minimum Necessary Requirements', 'When using or disclosing protected health information or when requesting protected health information from another covered entity or business associate, a covered entity or business associate must make reasonable efforts to limit protected health information to the minimum necessary to accomplish the intended purpose of the use, disclosure, or request.', 'Privacy Rule', 'Required', '45 CFR 164.502(b)'),
('164.502(e)', 'Business Associate Contracts', 'A covered entity may disclose protected health information to a business associate and may allow a business associate to create or receive protected health information on its behalf, if the covered entity obtains satisfactory assurance that the business associate will appropriately safeguard the information.', 'Privacy Rule', 'Required', '45 CFR 164.502(e)'),
('164.506', 'Uses and Disclosures to Carry Out Treatment, Payment, or Health Care Operations', 'A covered entity may use or disclose protected health information for its own treatment, payment, or health care operations.', 'Privacy Rule', 'Required', '45 CFR 164.506'),
('164.508', 'Uses and Disclosures for Which an Authorization is Required', 'A covered entity may not use or disclose protected health information without an authorization that is valid under this section, except as otherwise permitted or required by this subpart.', 'Privacy Rule', 'Required', '45 CFR 164.508'),
('164.510', 'Uses and Disclosures Requiring an Opportunity for the Individual to Agree or to Object', 'A covered entity may use or disclose protected health information, provided that the individual is informed in advance of the use or disclosure and has the opportunity to agree to or prohibit or restrict the use or disclosure.', 'Privacy Rule', 'Required', '45 CFR 164.510'),
('164.512', 'Uses and Disclosures for Which an Authorization or Opportunity to Agree or Object is Not Required', 'A covered entity may use or disclose protected health information without the written authorization of the individual, or the opportunity for the individual to agree or object, for certain specified purposes.', 'Privacy Rule', 'Required', '45 CFR 164.512'),
('164.514', 'Other Requirements Relating to Uses and Disclosures of Protected Health Information', 'A covered entity may use or disclose protected health information that meets the standard and implementation specifications for de-identification under paragraph (a) or (b) of this section.', 'Privacy Rule', 'Required', '45 CFR 164.514'),
('164.520', 'Notice of Privacy Practices for Protected Health Information', 'A covered entity must provide a notice that is written in plain language and that contains the elements described in this section.', 'Privacy Rule', 'Required', '45 CFR 164.520'),
('164.522', 'Rights to Request Privacy Protection for Protected Health Information', 'A covered entity must permit an individual to request that the covered entity restrict uses or disclosures of protected health information about the individual to carry out treatment, payment, or health care operations.', 'Privacy Rule', 'Required', '45 CFR 164.522'),
('164.524', 'Access of Individuals to Protected Health Information', 'An individual has a right of access to inspect and obtain a copy of protected health information about the individual in a designated record set, for as long as the protected health information is maintained in the designated record set.', 'Privacy Rule', 'Required', '45 CFR 164.524'),
('164.526', 'Amendment of Protected Health Information', 'An individual has the right to have a covered entity amend protected health information or a record about the individual in a designated record set for as long as the protected health information is maintained in the designated record set.', 'Privacy Rule', 'Required', '45 CFR 164.526'),
('164.528', 'Accounting of Disclosures of Protected Health Information', 'An individual has a right to receive an accounting of disclosures of protected health information made by a covered entity in the six years prior to the date on which the accounting is requested.', 'Privacy Rule', 'Required', '45 CFR 164.528'),
('164.530', 'Administrative Requirements', 'A covered entity must designate a privacy officer who is responsible for the development and implementation of the policies and procedures of the entity.', 'Privacy Rule', 'Required', '45 CFR 164.530'),
('164.532', 'Transition Provisions', 'A covered entity must comply with the applicable requirements of this subpart by the applicable compliance date set forth in § 164.534.', 'Privacy Rule', 'Required', '45 CFR 164.532'),
('164.534', 'Compliance Dates for Initial Implementation of the Privacy Standards', 'A covered entity must comply with the applicable requirements of this subpart by April 14, 2003, except that small health plans must comply by April 14, 2004.', 'Privacy Rule', 'Required', '45 CFR 164.534'),
('164.502(f)', 'Deceased Individuals', 'A covered entity must comply with the requirements of this subpart with respect to the protected health information of a deceased individual.', 'Privacy Rule', 'Required', '45 CFR 164.502(f)'),
('164.502(g)', 'Personal Representatives', 'A covered entity must, except as provided in paragraphs (g)(3) and (g)(5) of this section, treat a personal representative as the individual for purposes of this subchapter.', 'Privacy Rule', 'Required', '45 CFR 164.502(g)');

-- Breach Notification Rule (§164.400-164.414)
INSERT INTO hipaa_requirements (requirement_id, title, description, category, priority, regulation_reference) VALUES
('164.400', 'Applicability', 'The requirements of this subpart apply to covered entities and, in accordance with § 164.402(c), to business associates.', 'Breach Notification Rule', 'Required', '45 CFR 164.400'),
('164.402', 'Definitions', 'Breach means the acquisition, access, use, or disclosure of protected health information in a manner not permitted under subpart E of this part which compromises the security or privacy of the protected health information.', 'Breach Notification Rule', 'Required', '45 CFR 164.402'),
('164.404', 'Notification to Individuals', 'A covered entity shall, following the discovery of a breach of unsecured protected health information, notify each individual whose unsecured protected health information has been, or is reasonably believed by the covered entity to have been, accessed, acquired, used, or disclosed as a result of such breach.', 'Breach Notification Rule', 'Required', '45 CFR 164.404'),
('164.406', 'Notification to the Media', 'A covered entity that discovers a breach of unsecured protected health information shall notify prominent media outlets serving a State or jurisdiction, following the discovery of a breach described in § 164.404(a), if the unsecured protected health information of 500 or more individuals is, or is reasonably believed to have been, accessed, acquired, used, or disclosed during such breach.', 'Breach Notification Rule', 'Required', '45 CFR 164.406'),
('164.408', 'Notification to the Secretary', 'A covered entity shall, following the discovery of a breach of unsecured protected health information, notify the Secretary.', 'Breach Notification Rule', 'Required', '45 CFR 164.408'),
('164.410', 'Notification by a Business Associate', 'A business associate shall, following the discovery of a breach of unsecured protected health information, notify the covered entity of such breach.', 'Breach Notification Rule', 'Required', '45 CFR 164.410'),
('164.412', 'Law Enforcement Delay', 'If a law enforcement official states to a covered entity or business associate that a notification, notice, or posting required under this subpart would impede a criminal investigation or cause damage to national security, the covered entity or business associate shall delay such notification, notice, or posting for the time period specified by the official.', 'Breach Notification Rule', 'Required', '45 CFR 164.412'),
('164.414', 'Administrative Requirements and Burden of Proof', 'A covered entity or business associate shall have the burden of demonstrating that all notifications were made as required by this subpart or that the use or disclosure did not constitute a breach, as defined in § 164.402.', 'Breach Notification Rule', 'Required', '45 CFR 164.414');

SELECT 'Sample HIPAA requirements inserted successfully!' as status,
       COUNT(*) as total_requirements
FROM hipaa_requirements;
