-- Create AI Analysis Results Table
CREATE TABLE IF NOT EXISTS ai_analysis_results (
    id SERIAL PRIMARY KEY,
    analysis_type VARCHAR(100) NOT NULL,
    analysis_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_ai_analysis_type ON ai_analysis_results(analysis_type);
CREATE INDEX IF NOT EXISTS idx_ai_analysis_created_at ON ai_analysis_results(created_at DESC);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_ai_analysis_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_ai_analysis_updated_at
    BEFORE UPDATE ON ai_analysis_results
    FOR EACH ROW
    EXECUTE FUNCTION update_ai_analysis_updated_at();

-- Insert sample AI analysis data
INSERT INTO ai_analysis_results (analysis_type, analysis_content) VALUES
('risk_exposure', '🎯 EXECUTIVE RISK EXPOSURE ANALYSIS
Generated by AI GRC Engine v2.0

Current organizational risk posture: MODERATE-HIGH
Critical vulnerabilities identified: 23 high-priority items
Recommended immediate actions: 8 strategic initiatives
Estimated risk reduction potential: 67% within 6 months

STRATEGIC RISK PRIORITIES:
▶ Cybersecurity Infrastructure (Risk Score: 8.7/10)
▶ Regulatory Compliance Gaps (Risk Score: 7.9/10)
▶ Third-Party Risk Exposure (Risk Score: 7.2/10)'),

('threat_landscape', '🛡️ CYBERSECURITY THREAT LANDSCAPE ANALYSIS
AI-Powered Threat Intelligence Report

Current threat level: ELEVATED (7.8/10)
Active threat campaigns: 12 targeting healthcare sector
Zero-day vulnerabilities: 3 affecting our technology stack
Ransomware activity: 340% increase in healthcare attacks

SECTOR-SPECIFIC THREATS:
🎯 Healthcare-Targeted Campaigns
🎯 Supply Chain Attacks
🎯 Advanced Persistent Threats'),

('compliance_remediation', '📋 HIPAA COMPLIANCE REMEDIATION ANALYSIS
AI-Powered Regulatory Gap Assessment

Overall HIPAA compliance score: 73% (Target: 95%)
Critical gaps identified: 23 high-priority items
Administrative safeguards: 78% compliant
Physical safeguards: 85% compliant
Technical safeguards: 67% compliant

CRITICAL COMPLIANCE GAPS:
🚨 Administrative Safeguards
🚨 Physical Safeguards  
🚨 Technical Safeguards');

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ai_analysis_results TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE ai_analysis_results_id_seq TO PUBLIC;
