-- Insert 50 comprehensive ISO 27001 risk samples with all fields populated
-- Clear existing data first
TRUNCATE TABLE iso27001_risks RESTART IDENTITY CASCADE;

-- Insert 50 sample ISO 27001 risks with all fields populated
INSERT INTO iso27001_risks (
    risk_id, title, description, category, likelihood, impact, owner, treatment_plan, 
    residual_likelihood, residual_impact, residual_risk, last_reviewed, next_review, 
    controls, assets, control_assessment, risk_treatment
) VALUES
('ISO-001', 'Unauthorized Access to Customer Database', 'Risk of unauthorized personnel gaining access to sensitive customer information stored in the primary customer database through weak authentication mechanisms or privilege escalation attacks.', 'Access Control', 4, 5, 'John Smith - CISO', 'Implement multi-factor authentication for all database access, conduct quarterly access reviews, deploy privileged access management solution, and establish real-time monitoring for suspicious database activities.', 2, 3, 6, '2024-01-15', '2024-04-15', ARRAY['A.9.1.1', 'A.9.2.1', 'A.9.4.2', 'A.12.4.1'], ARRAY['Customer Database', 'CRM System', 'Authentication Server'], 'Current access controls are partially effective but lack comprehensive monitoring. MFA implementation is 60% complete across critical systems.', 'Mitigate'),

('ISO-002', 'Data Loss Due to Ransomware Attack', 'Risk of critical business data being encrypted or destroyed by ransomware, leading to operational disruption and potential data loss if backup systems are compromised.', 'Malware Protection', 3, 5, 'Sarah Johnson - IT Director', 'Deploy advanced endpoint detection and response (EDR), implement immutable backup solutions, conduct regular backup testing, and establish incident response procedures for ransomware events.', 2, 4, 8, '2024-01-20', '2024-04-20', ARRAY['A.12.2.1', 'A.12.3.1', 'A.16.1.1', 'A.17.1.2'], ARRAY['File Servers', 'Backup Systems', 'Workstations', 'Production Databases'], 'Anti-malware solutions are in place but need enhancement. Backup testing reveals some gaps in recovery procedures.', 'Mitigate'),

('ISO-003', 'Insider Threat from Privileged Users', 'Risk of malicious or negligent actions by employees with elevated system privileges, potentially leading to data theft, system sabotage, or unauthorized disclosure of sensitive information.', 'Human Resources', 3, 4, 'Mike Davis - HR Director', 'Implement user behavior analytics, establish segregation of duties, conduct background checks for privileged positions, and deploy data loss prevention (DLP) solutions.', 2, 3, 6, '2024-01-25', '2024-04-25', ARRAY['A.7.1.1', 'A.7.2.1', 'A.9.2.3', 'A.12.4.1'], ARRAY['All Systems', 'Sensitive Data Repositories', 'Administrative Interfaces'], 'Background screening processes are adequate but monitoring of privileged user activities needs improvement.', 'Mitigate'),

('ISO-004', 'Cloud Service Provider Security Breach', 'Risk of security incident at third-party cloud service provider resulting in unauthorized access to organizational data stored in cloud environments.', 'Supplier Management', 3, 4, 'Lisa Chen - Cloud Architect', 'Conduct thorough security assessments of cloud providers, implement cloud security posture management (CSPM), establish data encryption in transit and at rest, and develop cloud incident response procedures.', 2, 3, 6, '2024-02-01', '2024-05-01', ARRAY['A.15.1.1', 'A.15.2.1', 'A.10.1.1', 'A.13.2.1'], ARRAY['Cloud Infrastructure', 'SaaS Applications', 'Cloud Storage'], 'Cloud security controls are partially implemented. Need to enhance monitoring and incident response capabilities.', 'Mitigate'),

('ISO-005', 'Physical Security Breach at Data Center', 'Risk of unauthorized physical access to data center facilities, potentially leading to theft of equipment, data compromise, or service disruption.', 'Physical Security', 2, 4, 'Tom Wilson - Facilities Manager', 'Upgrade physical access controls with biometric authentication, install comprehensive CCTV surveillance, deploy environmental monitoring systems, and establish 24/7 security presence.', 1, 3, 3, '2024-02-05', '2024-05-05', ARRAY['A.11.1.1', 'A.11.1.2', 'A.11.2.1', 'A.11.1.4'], ARRAY['Data Center', 'Server Equipment', 'Network Infrastructure'], 'Physical security measures are adequate but need enhancement in monitoring and access logging.', 'Mitigate'),

('ISO-006', 'Email Phishing and Social Engineering', 'Risk of employees falling victim to phishing attacks and social engineering tactics, potentially leading to credential compromise and unauthorized system access.', 'Human Resources', 4, 3, 'Anna Rodriguez - Security Awareness Manager', 'Implement comprehensive security awareness training, deploy advanced email security solutions, conduct regular phishing simulations, and establish incident reporting procedures.', 3, 2, 6, '2024-02-10', '2024-05-10', ARRAY['A.7.2.2', 'A.13.2.3', 'A.16.1.2'], ARRAY['Email System', 'User Workstations', 'Web Browsers'], 'Security awareness training is ongoing but phishing simulation results show room for improvement.', 'Mitigate'),

('ISO-007', 'Cryptographic Key Management Failure', 'Risk of cryptographic keys being compromised, improperly managed, or lost, leading to unauthorized decryption of sensitive data and potential compliance violations.', 'Cryptography', 2, 5, 'David Kim - Cryptography Officer', 'Implement hardware security modules (HSM), establish key lifecycle management procedures, deploy automated key rotation, and conduct regular cryptographic audits.', 1, 4, 4, '2024-02-15', '2024-05-15', ARRAY['A.10.1.1', 'A.10.1.2'], ARRAY['Encryption Systems', 'Certificate Authority', 'Secure Communications'], 'Key management processes are documented but lack automation and comprehensive monitoring.', 'Mitigate'),

('ISO-008', 'Business Continuity Plan Failure', 'Risk of inability to maintain critical business operations during major disruptions such as natural disasters, cyber attacks, or infrastructure failures.', 'Business Continuity', 2, 5, 'Emma Thompson - BCP Coordinator', 'Develop comprehensive business continuity plans, establish alternate processing sites, implement redundant systems, and conduct regular disaster recovery testing.', 1, 4, 4, '2024-02-20', '2024-05-20', ARRAY['A.17.1.1', 'A.17.1.2', 'A.17.2.1'], ARRAY['Critical Systems', 'Business Processes', 'Communication Systems'], 'Business continuity plans exist but need regular testing and updates to address current threat landscape.', 'Mitigate'),

('ISO-009', 'Software Vulnerability Exploitation', 'Risk of attackers exploiting known or zero-day vulnerabilities in operating systems, applications, and network devices to gain unauthorized access or disrupt services.', 'System Maintenance', 3, 4, 'Robert Brown - System Administrator', 'Implement automated patch management, deploy vulnerability scanning tools, establish vulnerability assessment procedures, and maintain software inventory.', 2, 3, 6, '2024-02-25', '2024-05-25', ARRAY['A.12.6.1', 'A.14.2.3', 'A.12.5.1'], ARRAY['Operating Systems', 'Applications', 'Network Devices'], 'Patch management processes are in place but need improvement in testing and deployment timelines.', 'Mitigate'),

('ISO-010', 'Network Segmentation Failure', 'Risk of lateral movement by attackers due to inadequate network segmentation, allowing compromise of critical systems from less secure network segments.', 'Network Security', 3, 4, 'Jennifer Lee - Network Security Manager', 'Implement network micro-segmentation, deploy next-generation firewalls, establish network access control (NAC), and conduct regular network security assessments.', 2, 3, 6, '2024-03-01', '2024-06-01', ARRAY['A.13.1.1', 'A.13.1.3', 'A.9.1.2'], ARRAY['Network Infrastructure', 'Firewalls', 'Switches and Routers'], 'Network segmentation is partially implemented but needs enhancement for critical system isolation.', 'Mitigate'),

('ISO-011', 'Mobile Device Security Compromise', 'Risk of sensitive corporate data being accessed or stolen through compromised mobile devices used by employees for business purposes.', 'Mobile Security', 3, 3, 'Mark Taylor - Mobile Security Lead', 'Implement mobile device management (MDM), establish BYOD policies, deploy mobile application management (MAM), and conduct regular mobile security assessments.', 2, 2, 4, '2024-03-05', '2024-06-05', ARRAY['A.6.2.1', 'A.8.1.3', 'A.13.2.1'], ARRAY['Mobile Devices', 'Mobile Applications', 'Corporate Email'], 'MDM solution is deployed but policy enforcement and compliance monitoring need improvement.', 'Mitigate'),

('ISO-012', 'Database Injection Attack', 'Risk of SQL injection and other database attacks leading to unauthorized data access, data manipulation, or complete database compromise.', 'Application Security', 3, 4, 'Patricia Garcia - Application Security Lead', 'Implement input validation and parameterized queries, deploy web application firewalls (WAF), conduct regular code reviews, and perform penetration testing.', 2, 3, 6, '2024-03-10', '2024-06-10', ARRAY['A.14.2.1', 'A.14.2.5', 'A.14.2.8'], ARRAY['Web Applications', 'Databases', 'API Endpoints'], 'Application security controls are in development but need comprehensive implementation across all applications.', 'Mitigate'),

('ISO-013', 'Third-Party Vendor Data Breach', 'Risk of data breach occurring at third-party vendors who have access to organizational data, potentially exposing sensitive information.', 'Supplier Management', 3, 4, 'Steven Martinez - Vendor Management', 'Conduct vendor security assessments, implement data processing agreements, establish vendor monitoring procedures, and develop incident response coordination with vendors.', 2, 3, 6, '2024-03-15', '2024-06-15', ARRAY['A.15.1.1', 'A.15.1.2', 'A.15.2.1'], ARRAY['Vendor Systems', 'Shared Data', 'Integration Points'], 'Vendor assessment processes are established but need enhancement in ongoing monitoring and compliance verification.', 'Mitigate'),

('ISO-014', 'Backup System Failure', 'Risk of backup systems failing during critical recovery operations, leading to permanent data loss and extended business disruption.', 'Data Protection', 2, 5, 'Michelle White - Backup Administrator', 'Implement redundant backup systems, establish automated backup verification, conduct regular restore testing, and maintain offsite backup copies.', 1, 4, 4, '2024-03-20', '2024-06-20', ARRAY['A.12.3.1', 'A.17.1.2'], ARRAY['Backup Systems', 'Storage Arrays', 'Archive Systems'], 'Backup systems are operational but testing procedures need improvement to ensure reliable recovery.', 'Mitigate'),

('ISO-015', 'Privileged Account Compromise', 'Risk of administrative and service accounts being compromised, providing attackers with elevated access to critical systems and sensitive data.', 'Access Control', 4, 4, 'Christopher Johnson - Identity Management', 'Implement privileged access management (PAM), establish just-in-time access, deploy session monitoring, and conduct regular privileged account audits.', 2, 3, 6, '2024-03-25', '2024-06-25', ARRAY['A.9.2.3', 'A.9.2.4', 'A.9.2.5'], ARRAY['Administrative Systems', 'Service Accounts', 'Domain Controllers'], 'Privileged account management is partially implemented but needs comprehensive monitoring and access controls.', 'Mitigate'),

('ISO-016', 'IoT Device Security Vulnerabilities', 'Risk of Internet of Things (IoT) devices being compromised and used as entry points for network attacks or data exfiltration.', 'IoT Security', 3, 3, 'Amanda Davis - IoT Security Specialist', 'Implement IoT device inventory and management, establish network segmentation for IoT devices, deploy IoT security monitoring, and maintain device firmware updates.', 2, 2, 4, '2024-03-30', '2024-06-30', ARRAY['A.8.1.1', 'A.13.1.3', 'A.12.6.1'], ARRAY['IoT Devices', 'Sensor Networks', 'Building Management Systems'], 'IoT security framework is in development but device inventory and monitoring capabilities need enhancement.', 'Mitigate'),

('ISO-017', 'Remote Work Security Risks', 'Risk of security incidents arising from employees working remotely with inadequate security controls and potentially unsecured home networks.', 'Remote Access', 3, 3, 'Brian Wilson - Remote Work Security', 'Implement secure VPN solutions, establish remote work security policies, deploy endpoint protection for remote devices, and provide security awareness training for remote workers.', 2, 2, 4, '2024-04-01', '2024-07-01', ARRAY['A.6.2.2', 'A.13.2.1', 'A.11.2.6'], ARRAY['Remote Access Systems', 'VPN Infrastructure', 'Home Office Equipment'], 'Remote work security measures are in place but need enhancement in monitoring and policy enforcement.', 'Mitigate'),

('ISO-018', 'API Security Vulnerabilities', 'Risk of application programming interfaces (APIs) being exploited to gain unauthorized access to systems and data through authentication bypass or injection attacks.', 'API Security', 3, 4, 'Nicole Anderson - API Security Lead', 'Implement API gateway security, establish API authentication and authorization, deploy API monitoring and rate limiting, and conduct regular API security testing.', 2, 3, 6, '2024-04-05', '2024-07-05', ARRAY['A.14.1.3', 'A.9.4.1', 'A.13.1.1'], ARRAY['API Endpoints', 'Web Services', 'Integration Platforms'], 'API security controls are being implemented but need comprehensive coverage across all API endpoints.', 'Mitigate'),

('ISO-019', 'Data Classification and Handling Errors', 'Risk of sensitive data being mishandled, improperly classified, or inadequately protected due to lack of clear data governance policies and procedures.', 'Data Governance', 3, 3, 'Kevin Thompson - Data Governance Officer', 'Implement data classification framework, establish data handling procedures, deploy data loss prevention (DLP) tools, and conduct data governance training.', 2, 2, 4, '2024-04-10', '2024-07-10', ARRAY['A.8.2.1', 'A.8.2.2', 'A.8.2.3'], ARRAY['Data Repositories', 'Document Management Systems', 'Email Systems'], 'Data classification policies exist but implementation and enforcement across all systems need improvement.', 'Mitigate'),

('ISO-020', 'Incident Response Plan Inadequacy', 'Risk of ineffective incident response due to outdated procedures, insufficient resources, or lack of coordination during security incidents.', 'Incident Management', 2, 4, 'Rachel Green - Incident Response Manager', 'Update incident response procedures, establish incident response team training, implement incident management tools, and conduct regular tabletop exercises.', 1, 3, 3, '2024-04-15', '2024-07-15', ARRAY['A.16.1.1', 'A.16.1.4', 'A.16.1.5'], ARRAY['Incident Response Systems', 'Communication Tools', 'Forensic Equipment'], 'Incident response procedures are documented but need regular testing and updates to address current threat landscape.', 'Mitigate'),

('ISO-021', 'Supply Chain Security Compromise', 'Risk of security vulnerabilities being introduced through compromised software or hardware components in the supply chain.', 'Supply Chain', 3, 4, 'Daniel Rodriguez - Supply Chain Security', 'Implement supply chain risk assessments, establish vendor security requirements, deploy software composition analysis, and maintain supplier security monitoring.', 2, 3, 6, '2024-04-20', '2024-07-20', ARRAY['A.15.1.3', 'A.14.2.7', 'A.15.2.1'], ARRAY['Software Components', 'Hardware Suppliers', 'Third-Party Libraries'], 'Supply chain security assessments are conducted but need enhancement in continuous monitoring and risk evaluation.', 'Mitigate'),

('ISO-022', 'Compliance Violation Penalties', 'Risk of regulatory penalties and legal consequences due to non-compliance with data protection regulations such as GDPR, HIPAA, or industry standards.', 'Compliance', 2, 4, 'Laura Martinez - Compliance Officer', 'Implement compliance monitoring tools, establish regulatory change management, conduct regular compliance audits, and maintain compliance documentation.', 1, 3, 3, '2024-04-25', '2024-07-25', ARRAY['A.18.1.1', 'A.18.2.1', 'A.18.2.2'], ARRAY['Compliance Systems', 'Audit Logs', 'Documentation Repositories'], 'Compliance monitoring is in place but needs automation and real-time alerting for potential violations.', 'Mitigate'),

('ISO-023', 'Password Security Weaknesses', 'Risk of unauthorized access due to weak password policies, password reuse, or compromised credentials being used across multiple systems.', 'Authentication', 3, 3, 'Gregory Lee - Authentication Manager', 'Implement strong password policies, deploy password managers, establish multi-factor authentication, and conduct regular password security assessments.', 2, 2, 4, '2024-04-30', '2024-07-30', ARRAY['A.9.4.3', 'A.9.2.4', 'A.9.4.2'], ARRAY['Authentication Systems', 'User Accounts', 'Password Databases'], 'Password policies are established but enforcement and user compliance need improvement.', 'Mitigate'),

('ISO-024', 'Social Media Security Risks', 'Risk of sensitive information disclosure or social engineering attacks through inappropriate use of social media platforms by employees.', 'Social Media', 2, 3, 'Stephanie Clark - Social Media Security', 'Establish social media usage policies, implement social media monitoring, conduct employee training on social media risks, and deploy social media security tools.', 1, 2, 2, '2024-05-05', '2024-08-05', ARRAY['A.7.2.2', 'A.8.1.3', 'A.13.2.1'], ARRAY['Social Media Accounts', 'Employee Devices', 'Corporate Communications'], 'Social media policies are in place but monitoring and enforcement capabilities need development.', 'Accept'),

('ISO-025', 'Wireless Network Security Gaps', 'Risk of unauthorized access to corporate networks through insecure wireless access points or rogue wireless devices.', 'Wireless Security', 3, 3, 'Timothy Brown - Wireless Security Lead', 'Implement enterprise wireless security, deploy wireless intrusion detection, establish guest network isolation, and conduct regular wireless security assessments.', 2, 2, 4, '2024-05-10', '2024-08-10', ARRAY['A.13.1.1', 'A.11.2.3', 'A.9.1.2'], ARRAY['Wireless Access Points', 'Wireless Controllers', 'Mobile Devices'], 'Wireless security controls are implemented but need enhancement in monitoring and rogue device detection.', 'Mitigate'),

('ISO-026', 'Email Security Threats', 'Risk of malware delivery, data exfiltration, or credential theft through email-based attacks including spam, phishing, and business email compromise.', 'Email Security', 4, 3, 'Vanessa White - Email Security Manager', 'Deploy advanced email security solutions, implement email encryption, establish email retention policies, and conduct email security awareness training.', 3, 2, 6, '2024-05-15', '2024-08-15', ARRAY['A.13.2.3', 'A.10.1.1', 'A.7.2.2'], ARRAY['Email Servers', 'Email Clients', 'Email Gateways'], 'Email security solutions are deployed but need enhancement in advanced threat detection and user training.', 'Mitigate'),

('ISO-027', 'Database Access Control Failures', 'Risk of unauthorized database access due to inadequate access controls, excessive privileges, or compromised database credentials.', 'Database Security', 3, 4, 'Harold Johnson - Database Administrator', 'Implement database access controls, establish database activity monitoring, deploy database encryption, and conduct regular database security audits.', 2, 3, 6, '2024-05-20', '2024-08-20', ARRAY['A.9.4.1', 'A.12.4.1', 'A.10.1.1'], ARRAY['Production Databases', 'Database Servers', 'Database Management Tools'], 'Database security controls are partially implemented but need comprehensive access monitoring and audit capabilities.', 'Mitigate'),

('ISO-028', 'Change Management Security Risks', 'Risk of security vulnerabilities being introduced through inadequate change management processes for systems, applications, and configurations.', 'Change Management', 2, 3, 'Olivia Davis - Change Management Lead', 'Implement secure change management procedures, establish change approval workflows, deploy configuration management tools, and conduct security reviews for all changes.', 1, 2, 2, '2024-05-25', '2024-08-25', ARRAY['A.12.1.2', 'A.14.2.2', 'A.12.1.4'], ARRAY['Production Systems', 'Configuration Management', 'Deployment Tools'], 'Change management processes are documented but need enhancement in security review and approval procedures.', 'Mitigate'),

('ISO-029', 'Virtualization Security Vulnerabilities', 'Risk of security breaches in virtualized environments due to hypervisor vulnerabilities, VM escape attacks, or inadequate virtual network security.', 'Virtualization', 3, 4, 'Peter Wilson - Virtualization Security', 'Implement hypervisor security hardening, establish virtual network segmentation, deploy VM security monitoring, and maintain virtualization security patches.', 2, 3, 6, '2024-05-30', '2024-08-30', ARRAY['A.13.1.3', 'A.12.6.1', 'A.11.2.1'], ARRAY['Hypervisors', 'Virtual Machines', 'Virtual Networks'], 'Virtualization security controls are in place but need enhancement in monitoring and threat detection.', 'Mitigate'),

('ISO-030', 'Log Management and Monitoring Gaps', 'Risk of security incidents going undetected due to inadequate log collection, analysis, or retention across critical systems and applications.', 'Logging and Monitoring', 3, 3, 'Samantha Martinez - Security Monitoring Lead', 'Implement centralized log management, establish security information and event management (SIEM), deploy automated log analysis, and maintain log retention policies.', 2, 2, 4, '2024-06-01', '2024-09-01', ARRAY['A.12.4.1', 'A.12.4.2', 'A.12.4.3'], ARRAY['Log Management Systems', 'SIEM Platform', 'Network Devices'], 'Log management infrastructure is deployed but needs enhancement in automated analysis and alerting capabilities.', 'Mitigate'),

('ISO-031', 'Container Security Vulnerabilities', 'Risk of security breaches in containerized applications due to vulnerable container images, misconfigurations, or inadequate runtime security.', 'Container Security', 3, 3, 'Jonathan Lee - Container Security Specialist', 'Implement container image scanning, establish container security policies, deploy runtime protection, and maintain container security monitoring.', 2, 2, 4, '2024-06-05', '2024-09-05', ARRAY['A.14.2.1', 'A.12.6.1', 'A.13.1.3'], ARRAY['Container Images', 'Container Runtime', 'Orchestration Platform'], 'Container security framework is in development but needs comprehensive implementation across all containerized applications.', 'Mitigate'),

('ISO-032', 'DevOps Security Integration Gaps', 'Risk of security vulnerabilities being introduced through inadequate security integration in DevOps processes and CI/CD pipelines.', 'DevSecOps', 3, 3, 'Ashley Thompson - DevSecOps Lead', 'Implement security in CI/CD pipelines, establish secure coding practices, deploy automated security testing, and conduct DevSecOps training.', 2, 2, 4, '2024-06-10', '2024-09-10', ARRAY['A.14.2.1', 'A.14.2.8', 'A.14.2.9'], ARRAY['CI/CD Pipelines', 'Source Code Repositories', 'Deployment Tools'], 'DevSecOps practices are being implemented but need enhancement in automated security testing and policy enforcement.', 'Mitigate'),

('ISO-033', 'Artificial Intelligence Security Risks', 'Risk of AI and machine learning systems being compromised, manipulated, or used maliciously, potentially leading to incorrect decisions or data breaches.', 'AI Security', 2, 4, 'Marcus Rodriguez - AI Security Researcher', 'Implement AI security frameworks, establish model validation procedures, deploy AI monitoring tools, and conduct AI security assessments.', 1, 3, 3, '2024-06-15', '2024-09-15', ARRAY['A.14.2.5', 'A.12.4.1', 'A.8.2.1'], ARRAY['AI Models', 'Machine Learning Platforms', 'Training Data'], 'AI security controls are in early development but need comprehensive framework implementation.', 'Mitigate'),

('ISO-034', 'Quantum Computing Threat to Cryptography', 'Risk of current cryptographic systems becoming vulnerable to quantum computing attacks, potentially compromising encrypted data and communications.', 'Quantum Security', 1, 5, 'Dr. Elizabeth Chen - Quantum Security Advisor', 'Research post-quantum cryptography, establish quantum-resistant algorithms, plan cryptographic migration strategy, and monitor quantum computing developments.', 1, 4, 4, '2024-06-20', '2024-09-20', ARRAY['A.10.1.1', 'A.10.1.2'], ARRAY['Encryption Systems', 'Digital Certificates', 'Secure Communications'], 'Quantum threat assessment is ongoing but post-quantum cryptography implementation planning is needed.', 'Accept'),

('ISO-035', 'Biometric Authentication Vulnerabilities', 'Risk of biometric authentication systems being spoofed, compromised, or failing, potentially allowing unauthorized access to secure systems.', 'Biometric Security', 2, 3, 'Ryan Garcia - Biometric Systems Manager', 'Implement multi-modal biometric systems, establish liveness detection, deploy biometric template protection, and conduct biometric security testing.', 1, 2, 2, '2024-06-25', '2024-09-25', ARRAY['A.9.4.2', 'A.11.1.2', 'A.9.2.1'], ARRAY['Biometric Scanners', 'Authentication Systems', 'Access Control Systems'], 'Biometric authentication is deployed but needs enhancement in anti-spoofing and template security.', 'Mitigate'),

('ISO-036', 'Blockchain Security Vulnerabilities', 'Risk of security vulnerabilities in blockchain implementations, smart contracts, or cryptocurrency systems leading to financial loss or data compromise.', 'Blockchain Security', 2, 4, 'Natalie Wilson - Blockchain Security Analyst', 'Implement blockchain security audits, establish smart contract testing, deploy blockchain monitoring, and maintain cryptocurrency security controls.', 1, 3, 3, '2024-06-30', '2024-09-30', ARRAY['A.14.2.8', 'A.10.1.1', 'A.15.1.1'], ARRAY['Blockchain Networks', 'Smart Contracts', 'Cryptocurrency Wallets'], 'Blockchain security framework is in development but needs comprehensive security audit and monitoring capabilities.', 'Mitigate'),

('ISO-037', 'Edge Computing Security Risks', 'Risk of security vulnerabilities in edge computing infrastructure due to distributed architecture, limited security controls, and remote management challenges.', 'Edge Security', 3, 3, 'Carlos Martinez - Edge Computing Security', 'Implement edge security frameworks, establish remote device management, deploy edge monitoring solutions, and maintain edge device security updates.', 2, 2, 4, '2024-07-05', '2024-10-05', ARRAY['A.11.2.6', 'A.13.1.3', 'A.12.6.1'], ARRAY['Edge Devices', 'Edge Networks', 'Remote Sensors'], 'Edge computing security controls are being developed but need comprehensive implementation across distributed infrastructure.', 'Mitigate'),

('ISO-038', 'Zero Trust Architecture Implementation Gaps', 'Risk of security breaches due to incomplete implementation of zero trust security principles, allowing lateral movement and privilege escalation.', 'Zero Trust', 3, 4, 'Diana Lee - Zero Trust Architect', 'Implement zero trust network architecture, establish identity verification, deploy micro-segmentation, and conduct zero trust maturity assessments.', 2, 3, 6, '2024-07-10', '2024-10-10', ARRAY['A.9.1.1', 'A.13.1.3', 'A.9.4.1'], ARRAY['Network Infrastructure', 'Identity Systems', 'Access Control Systems'], 'Zero trust implementation is in progress but needs comprehensive coverage across all network segments and applications.', 'Mitigate'),

('ISO-039', 'Privacy Engineering Compliance Gaps', 'Risk of privacy violations due to inadequate privacy-by-design implementation in systems and processes, leading to regulatory penalties and reputation damage.', 'Privacy Engineering', 2, 4, 'Isabella Rodriguez - Privacy Engineer', 'Implement privacy-by-design principles, establish data minimization practices, deploy privacy impact assessments, and maintain privacy compliance monitoring.', 1, 3, 3, '2024-07-15', '2024-10-15', ARRAY['A.18.1.4', 'A.8.2.1', 'A.18.1.1'], ARRAY['Data Processing Systems', 'Customer Data', 'Privacy Management Tools'], 'Privacy engineering practices are being developed but need systematic implementation across all data processing activities.', 'Mitigate'),

('ISO-040', 'Threat Intelligence Integration Gaps', 'Risk of security incidents due to inadequate threat intelligence integration, resulting in delayed threat detection and response.', 'Threat Intelligence', 3, 3, 'Alexander Brown - Threat Intelligence Analyst', 'Implement threat intelligence platforms, establish threat hunting capabilities, deploy automated threat feeds, and conduct threat intelligence training.', 2, 2, 4, '2024-07-20', '2024-10-20', ARRAY['A.12.6.1', 'A.16.1.4', 'A.12.4.1'], ARRAY['Threat Intelligence Platforms', 'Security Tools', 'Incident Response Systems'], 'Threat intelligence capabilities are being developed but need enhancement in automation and integration with security tools.', 'Mitigate'),

('ISO-041', 'Security Orchestration Automation Failures', 'Risk of delayed incident response and inefficient security operations due to lack of security orchestration and automated response capabilities.', 'Security Automation', 2, 3, 'Melissa Davis - Security Automation Lead', 'Implement security orchestration platforms, establish automated response playbooks, deploy security automation tools, and conduct automation testing.', 1, 2, 2, '2024-07-25', '2024-10-25', ARRAY['A.16.1.5', 'A.12.1.1', 'A.16.1.4'], ARRAY['Security Orchestration Platform', 'Incident Response Tools', 'Security Analytics'], 'Security automation framework is in development but needs comprehensive playbook development and testing.', 'Mitigate'),

('ISO-042', 'Digital Forensics Capability Gaps', 'Risk of inadequate incident investigation and evidence collection due to insufficient digital forensics capabilities and procedures.', 'Digital Forensics', 2, 3, 'Christopher Wilson - Digital Forensics Specialist', 'Establish digital forensics procedures, implement forensics tools and capabilities, conduct forensics training, and maintain evidence handling protocols.', 1, 2, 2, '2024-07-30', '2024-10-30', ARRAY['A.16.1.7', 'A.16.1.6', 'A.12.4.2'], ARRAY['Forensics Tools', 'Evidence Storage', 'Investigation Systems'], 'Digital forensics capabilities are basic but need enhancement in tools, training, and procedures.', 'Mitigate'),

('ISO-043', 'Security Metrics and KPI Gaps', 'Risk of ineffective security program management due to lack of comprehensive security metrics, KPIs, and performance measurement.', 'Security Metrics', 2, 2, 'Jennifer Martinez - Security Metrics Analyst', 'Implement security metrics framework, establish KPI dashboards, deploy security measurement tools, and conduct regular security performance reviews.', 1, 1, 1, '2024-08-01', '2024-11-01', ARRAY['A.18.2.1', 'A.5.1.2', 'A.12.1.1'], ARRAY['Security Dashboards', 'Metrics Tools', 'Reporting Systems'], 'Security metrics program is in early development but needs comprehensive framework and automation.', 'Accept'),

('ISO-044', 'Third-Party Risk Assessment Gaps', 'Risk of security incidents from third-party vendors due to inadequate risk assessment and ongoing monitoring of vendor security posture.', 'Third-Party Risk', 3, 4, 'Robert Lee - Third-Party Risk Manager', 'Implement vendor risk assessment framework, establish continuous vendor monitoring, deploy third-party risk management tools, and maintain vendor security scorecards.', 2, 3, 6, '2024-08-05', '2024-11-05', ARRAY['A.15.1.1', 'A.15.2.1', 'A.15.2.2'], ARRAY['Vendor Management Systems', 'Risk Assessment Tools', 'Vendor Portals'], 'Third-party risk assessment processes are established but need enhancement in continuous monitoring and automation.', 'Mitigate'),

('ISO-045', 'Security Training and Awareness Gaps', 'Risk of security incidents due to inadequate security awareness training and lack of security culture among employees and contractors.', 'Security Training', 3, 3, 'Amanda Thompson - Security Training Manager', 'Implement comprehensive security training programs, establish role-based training, deploy security awareness platforms, and conduct regular training effectiveness assessments.', 2, 2, 4, '2024-08-10', '2024-11-10', ARRAY['A.7.2.2', 'A.7.2.1', 'A.16.1.2'], ARRAY['Training Platforms', 'E-Learning Systems', 'Assessment Tools'], 'Security training programs are in place but need enhancement in personalization and effectiveness measurement.', 'Mitigate'),

('ISO-046', 'Regulatory Change Management Risks', 'Risk of non-compliance due to failure to identify, assess, and implement changes required by new or updated regulations and standards.', 'Regulatory Management', 2, 4, 'Victoria Garcia - Regulatory Affairs Manager', 'Implement regulatory change monitoring, establish compliance impact assessments, deploy regulatory management tools, and maintain regulatory change procedures.', 1, 3, 3, '2024-08-15', '2024-11-15', ARRAY['A.18.1.1', 'A.18.2.2', 'A.5.1.2'], ARRAY['Compliance Management Systems', 'Regulatory Databases', 'Change Management Tools'], 'Regulatory change management processes are documented but need automation and proactive monitoring capabilities.', 'Mitigate'),

('ISO-047', 'Security Architecture Review Gaps', 'Risk of security vulnerabilities due to inadequate security architecture reviews for new systems, applications, and infrastructure changes.', 'Security Architecture', 2, 3, 'Thomas Rodriguez - Security Architect', 'Implement security architecture review processes, establish security design standards, deploy architecture assessment tools, and conduct regular architecture security audits.', 1, 2, 2, '2024-08-20', '2024-11-20', ARRAY['A.14.1.1', 'A.14.2.5', 'A.13.1.1'], ARRAY['Architecture Documentation', 'Design Tools', 'Review Systems'], 'Security architecture review processes are established but need enhancement in automation and comprehensive coverage.', 'Mitigate'),

('ISO-048', 'Crisis Communication Plan Inadequacy', 'Risk of reputational damage and stakeholder confusion during security incidents due to inadequate crisis communication plans and procedures.', 'Crisis Communication', 2, 3, 'Sarah Wilson - Crisis Communication Lead', 'Develop crisis communication plans, establish stakeholder notification procedures, implement communication tools, and conduct crisis communication training.', 1, 2, 2, '2024-08-25', '2024-11-25', ARRAY['A.16.1.2', 'A.6.1.4', 'A.7.2.2'], ARRAY['Communication Systems', 'Notification Tools', 'Media Relations'], 'Crisis communication plans exist but need regular testing and updates for current threat landscape.', 'Mitigate'),

('ISO-049', 'Security Budget and Resource Allocation Risks', 'Risk of inadequate security posture due to insufficient budget allocation and resource planning for security initiatives and operations.', 'Security Governance', 2, 4, 'Michael Brown - Security Finance Manager', 'Implement security budget planning, establish ROI metrics for security investments, deploy resource allocation tools, and conduct regular security investment reviews.', 1, 3, 3, '2024-08-30', '2024-11-30', ARRAY['A.6.1.1', 'A.5.1.1', 'A.18.2.1'], ARRAY['Budget Management Systems', 'Resource Planning Tools', 'Investment Tracking'], 'Security budget planning processes are in place but need enhancement in ROI measurement and strategic alignment.', 'Mitigate'),

('ISO-050', 'Emerging Technology Security Assessment Gaps', 'Risk of security vulnerabilities in emerging technologies due to lack of security assessment frameworks and expertise for new technology adoption.', 'Emerging Technology', 2, 3, 'Dr. Lisa Martinez - Emerging Technology Security', 'Establish emerging technology assessment framework, implement security research capabilities, deploy technology evaluation tools, and maintain emerging threat monitoring.', 1, 2, 2, '2024-09-01', '2024-12-01', ARRAY['A.14.1.1', 'A.12.6.1', 'A.15.1.3'], ARRAY['Research Labs', 'Evaluation Platforms', 'Technology Assessments'], 'Emerging technology security assessment capabilities are in development but need comprehensive framework and expertise.', 'Mitigate');

-- Update the sequence to continue from 51
SELECT setval('iso27001_risks_id_seq', 50, true);
