-- Insert 50 comprehensive incident samples with all fields populated
-- This script provides realistic incident data for testing and demonstration

-- First, let's check the current incidents table structure
-- Fields: id, incident_id, incident_title, incident_description, incident_type, 
--         severity, status, reported_by, assigned_to, reported_date, detected_date,
--         related_asset_id, related_risk_id, created_at, updated_at

INSERT INTO incidents (
    incident_id, incident_title, incident_description, incident_type,
    severity, status, reported_by, assigned_to, reported_date, detected_date,
    related_asset_id, related_risk_id
) VALUES 
-- Critical Security Incidents
(
    'INC-2024-001',
    'Advanced Persistent Threat Detection',
    'Sophisticated APT group identified attempting to establish persistence in corporate network. Multiple attack vectors detected including spear-phishing, lateral movement, and data exfiltration attempts. Threat actors demonstrated advanced techniques including living-off-the-land tactics and custom malware deployment.',
    'Advanced Persistent Threat',
    'Critical',
    'In Progress',
    'SOC Analyst - Sarah Chen',
    'CISO - Michael Rodriguez',
    '2024-01-15 08:30:00+00',
    '2024-01-15 08:15:00+00',
    1,
    1
),
(
    'INC-2024-002',
    'Ransomware Attack - Financial Systems',
    'Ransomware deployment detected on financial processing servers. Encryption process initiated but contained before completion. Threat actors demanded $2.5M in cryptocurrency. Systems isolated and recovery procedures activated. No data exfiltration confirmed.',
    'Ransomware',
    'Critical',
    'Resolved',
    'Network Admin - David Park',
    'Incident Response Team',
    '2024-01-14 14:45:00+00',
    '2024-01-14 14:30:00+00',
    2,
    2
),
(
    'INC-2024-003',
    'Data Breach - Customer Database',
    'Unauthorized access to customer database containing PII of 50,000+ customers. Breach occurred through compromised admin credentials. Data accessed includes names, addresses, phone numbers, and encrypted payment information. Regulatory notifications initiated.',
    'Data Breach',
    'Critical',
    'In Progress',
    'Database Admin - Lisa Wang',
    'Data Protection Officer',
    '2024-01-13 11:20:00+00',
    '2024-01-13 10:45:00+00',
    3,
    3
),
(
    'INC-2024-004',
    'Insider Threat - Privileged Access Abuse',
    'Privileged user detected accessing sensitive files outside normal work patterns. Unusual data download activity identified during off-hours. Employee terminated two weeks prior but access not properly revoked. Potential intellectual property theft under investigation.',
    'Insider Threat',
    'Critical',
    'Open',
    'HR Security - Jennifer Adams',
    'Security Team Lead',
    '2024-01-12 16:15:00+00',
    '2024-01-12 15:30:00+00',
    4,
    4
),
(
    'INC-2024-005',
    'Supply Chain Compromise',
    'Third-party software vendor compromised, affecting our production systems. Malicious code injected into software updates. Multiple organizations affected globally. Vendor relationship under review and systems being rebuilt from clean backups.',
    'Supply Chain Attack',
    'Critical',
    'In Progress',
    'Vendor Manager - Robert Kim',
    'Chief Technology Officer',
    '2024-01-11 09:00:00+00',
    '2024-01-11 08:30:00+00',
    5,
    5
),

-- High Severity Incidents
(
    'INC-2024-006',
    'Phishing Campaign - Executive Targeting',
    'Sophisticated spear-phishing campaign targeting C-level executives. Emails spoofed legitimate business partners requesting urgent wire transfers. Two executives nearly compromised before security awareness training kicked in. Campaign linked to known threat actor group.',
    'Phishing',
    'High',
    'Resolved',
    'Email Security - Amanda Foster',
    'Security Awareness Manager',
    '2024-01-10 13:45:00+00',
    '2024-01-10 13:20:00+00',
    1,
    6
),
(
    'INC-2024-007',
    'DDoS Attack - Public Web Services',
    'Distributed Denial of Service attack targeting public-facing web applications. Peak traffic reached 500 Gbps affecting customer portal and e-commerce platform. Attack lasted 6 hours before mitigation measures took effect. Revenue impact estimated at $150K.',
    'DDoS Attack',
    'High',
    'Closed',
    'Network Operations - Carlos Martinez',
    'Infrastructure Manager',
    '2024-01-09 10:30:00+00',
    '2024-01-09 10:15:00+00',
    2,
    7
),
(
    'INC-2024-008',
    'Malware Outbreak - Endpoint Systems',
    'Widespread malware infection across 200+ endpoint systems. Trojan delivered via compromised software download. Malware designed for credential harvesting and keylogging. All affected systems quarantined and undergoing remediation.',
    'Malware',
    'High',
    'In Progress',
    'Endpoint Security - Rachel Thompson',
    'IT Security Manager',
    '2024-01-08 15:20:00+00',
    '2024-01-08 15:00:00+00',
    3,
    8
),
(
    'INC-2024-009',
    'Unauthorized Network Access',
    'External threat actor gained unauthorized access to internal network through VPN vulnerability. Lateral movement detected across multiple network segments. No data exfiltration confirmed but extensive reconnaissance activity observed.',
    'Network Intrusion',
    'High',
    'In Progress',
    'Network Security - Kevin Lee',
    'Network Security Lead',
    '2024-01-07 12:10:00+00',
    '2024-01-07 11:45:00+00',
    4,
    9
),
(
    'INC-2024-010',
    'Cloud Storage Misconfiguration',
    'Public cloud storage bucket discovered with sensitive company data exposed to internet. Bucket contained financial reports, employee records, and strategic planning documents. Exposure duration estimated at 3 weeks before discovery.',
    'Data Exposure',
    'High',
    'Resolved',
    'Cloud Admin - Maria Gonzalez',
    'Cloud Security Architect',
    '2024-01-06 14:30:00+00',
    '2024-01-06 14:15:00+00',
    5,
    10
),
(
    'INC-2024-011',
    'Business Email Compromise',
    'CEO email account compromised through credential stuffing attack. Threat actor sent fraudulent payment requests to finance team. $75K wire transfer initiated before fraud detection systems triggered alerts. Funds recovery in progress.',
    'Business Email Compromise',
    'High',
    'Open',
    'Executive Assistant - Patricia Davis',
    'Finance Security Manager',
    '2024-01-05 11:45:00+00',
    '2024-01-05 11:30:00+00',
    1,
    11
),
(
    'INC-2024-012',
    'API Security Breach',
    'Vulnerability in REST API allowed unauthorized data access. Attackers exploited broken authentication to access customer order history and payment methods. API serving 10M+ requests daily. Immediate patching and monitoring implemented.',
    'API Vulnerability',
    'High',
    'Resolved',
    'API Developer - James Wilson',
    'Application Security Lead',
    '2024-01-04 16:00:00+00',
    '2024-01-04 15:45:00+00',
    2,
    12
),
(
    'INC-2024-013',
    'Physical Security Breach',
    'Unauthorized individual gained access to data center through tailgating. Person spent 45 minutes in facility before being detected by security cameras. No evidence of tampering with equipment but full security review initiated.',
    'Physical Breach',
    'High',
    'Closed',
    'Security Guard - Thomas Brown',
    'Physical Security Manager',
    '2024-01-03 18:20:00+00',
    '2024-01-03 18:15:00+00',
    3,
    13
),
(
    'INC-2024-014',
    'Mobile Device Compromise',
    'Executive mobile device infected with spyware through malicious app installation. Device contained access to corporate email, calendar, and sensitive documents. Remote wipe performed and device forensics initiated.',
    'Mobile Security',
    'High',
    'In Progress',
    'Mobile Admin - Susan Miller',
    'Mobile Security Specialist',
    '2024-01-02 09:30:00+00',
    '2024-01-02 09:15:00+00',
    4,
    14
),
(
    'INC-2024-015',
    'Database Injection Attack',
    'SQL injection vulnerability exploited in customer portal application. Attacker gained read access to user credentials and personal information. Vulnerability patched and affected users notified for password reset.',
    'SQL Injection',
    'High',
    'Resolved',
    'Web Developer - Andrew Taylor',
    'Application Security Team',
    '2024-01-01 20:45:00+00',
    '2024-01-01 20:30:00+00',
    5,
    15
),

-- Medium Severity Incidents
(
    'INC-2024-016',
    'Suspicious Email Activity',
    'Unusual email patterns detected from marketing department accounts. Multiple accounts sending emails outside normal business hours with suspicious attachments. Potential account compromise under investigation.',
    'Email Security',
    'Medium',
    'Open',
    'Email Admin - Michelle Garcia',
    'Email Security Analyst',
    '2023-12-31 14:20:00+00',
    '2023-12-31 14:10:00+00',
    1,
    16
),
(
    'INC-2024-017',
    'Firewall Rule Violation',
    'Multiple attempts to access blocked websites and services detected from internal network. Traffic patterns suggest potential malware communication or policy violation. User education and additional monitoring implemented.',
    'Policy Violation',
    'Medium',
    'In Progress',
    'Firewall Admin - Daniel Rodriguez',
    'Network Security Analyst',
    '2023-12-30 11:15:00+00',
    '2023-12-30 11:00:00+00',
    2,
    17
),
(
    'INC-2024-018',
    'Backup System Failure',
    'Critical system backup failed for third consecutive day. Backup verification shows incomplete data sets and corruption in archive files. Risk of data loss if primary systems fail. Backup infrastructure review initiated.',
    'System Failure',
    'Medium',
    'Open',
    'Backup Admin - Laura Johnson',
    'Infrastructure Team Lead',
    '2023-12-29 02:30:00+00',
    '2023-12-29 02:00:00+00',
    3,
    18
),
(
    'INC-2024-019',
    'Unauthorized Software Installation',
    'Unapproved software detected on multiple workstations including peer-to-peer applications and unauthorized remote access tools. Software poses security risk and violates corporate policy. Removal and user training in progress.',
    'Policy Violation',
    'Medium',
    'In Progress',
    'Desktop Support - Christopher Lee',
    'IT Compliance Manager',
    '2023-12-28 13:45:00+00',
    '2023-12-28 13:30:00+00',
    4,
    19
),
(
    'INC-2024-020',
    'VPN Connection Anomalies',
    'Unusual VPN connection patterns detected including connections from high-risk geographic locations and multiple simultaneous sessions from single accounts. Enhanced monitoring and user verification implemented.',
    'Network Security',
    'Medium',
    'Resolved',
    'VPN Admin - Jessica Martinez',
    'Remote Access Manager',
    '2023-12-27 16:10:00+00',
    '2023-12-27 15:55:00+00',
    5,
    20
),
(
    'INC-2024-021',
    'Antivirus Definition Failure',
    'Antivirus systems failed to update with latest threat definitions for 48 hours. Systems remained vulnerable to newly discovered threats during outage period. Manual updates deployed and monitoring enhanced.',
    'System Failure',
    'Medium',
    'Closed',
    'Antivirus Admin - Ryan Thompson',
    'Endpoint Protection Lead',
    '2023-12-26 08:20:00+00',
    '2023-12-26 08:00:00+00',
    1,
    21
),
(
    'INC-2024-022',
    'Wireless Network Intrusion Attempt',
    'Multiple attempts to connect to corporate wireless network using brute force attacks on WPA2 encryption. Attempts originated from parking lot area. Physical security notified and network monitoring increased.',
    'Wireless Security',
    'Medium',
    'Resolved',
    'Wireless Admin - Nicole Davis',
    'Wireless Security Specialist',
    '2023-12-25 19:30:00+00',
    '2023-12-25 19:15:00+00',
    2,
    22
),
(
    'INC-2024-023',
    'USB Device Policy Violation',
    'Unauthorized USB devices detected connecting to corporate workstations. Devices include personal storage drives and unknown hardware. Auto-run disabled and device scanning implemented. User policy training scheduled.',
    'Policy Violation',
    'Medium',
    'In Progress',
    'Desktop Security - Brandon Wilson',
    'Endpoint Security Analyst',
    '2023-12-24 12:45:00+00',
    '2023-12-24 12:30:00+00',
    3,
    23
),
(
    'INC-2024-024',
    'Certificate Expiration Alert',
    'Multiple SSL certificates approaching expiration within 30 days including critical web services and internal applications. Service disruption possible if not renewed promptly. Certificate management process review initiated.',
    'Certificate Management',
    'Medium',
    'Open',
    'Certificate Admin - Stephanie Brown',
    'PKI Administrator',
    '2023-12-23 10:15:00+00',
    '2023-12-23 10:00:00+00',
    4,
    24
),
(
    'INC-2024-025',
    'Log Management System Overload',
    'Security log management system experiencing capacity issues with log ingestion delays up to 4 hours. Critical security events may not be detected in timely manner. Storage expansion and optimization in progress.',
    'System Performance',
    'Medium',
    'In Progress',
    'Log Admin - Matthew Garcia',
    'SIEM Administrator',
    '2023-12-22 15:30:00+00',
    '2023-12-22 15:15:00+00',
    5,
    25
),
(
    'INC-2024-026',
    'Patch Management Delays',
    'Critical security patches delayed beyond policy window for 150+ systems. Delay caused by compatibility testing issues and change management bottlenecks. Emergency patching procedures activated for high-risk systems.',
    'Patch Management',
    'Medium',
    'Open',
    'Patch Admin - Ashley Rodriguez',
    'Systems Management Lead',
    '2023-12-21 09:45:00+00',
    '2023-12-21 09:30:00+00',
    1,
    26
),
(
    'INC-2024-027',
    'Identity Management Sync Issues',
    'User account synchronization failures between Active Directory and cloud applications. Some users unable to access required systems while others retain access after termination. Manual verification and cleanup initiated.',
    'Identity Management',
    'Medium',
    'In Progress',
    'Identity Admin - Joshua Martinez',
    'Identity Management Specialist',
    '2023-12-20 14:20:00+00',
    '2023-12-20 14:05:00+00',
    2,
    27
),
(
    'INC-2024-028',
    'Third-Party Integration Failure',
    'Security monitoring integration with third-party vendor systems experiencing connectivity issues. Real-time threat intelligence feeds interrupted. Backup monitoring procedures activated while troubleshooting continues.',
    'Integration Failure',
    'Medium',
    'Resolved',
    'Integration Admin - Amanda Johnson',
    'Security Integration Lead',
    '2023-12-19 11:30:00+00',
    '2023-12-19 11:15:00+00',
    3,
    28
),
(
    'INC-2024-029',
    'Data Classification Violations',
    'Sensitive documents discovered in unsecured file shares without proper classification labels. Documents include financial data and employee records. Data loss prevention rules updated and user training scheduled.',
    'Data Protection',
    'Medium',
    'Open',
    'Data Admin - Tyler Wilson',
    'Data Protection Analyst',
    '2023-12-18 16:45:00+00',
    '2023-12-18 16:30:00+00',
    4,
    29
),
(
    'INC-2024-030',
    'Security Awareness Training Gaps',
    'Quarterly security awareness training completion rates below 80% threshold. Multiple departments showing low participation including high-risk roles. Mandatory training enforcement and management escalation initiated.',
    'Training Compliance',
    'Medium',
    'In Progress',
    'Training Admin - Samantha Davis',
    'Security Awareness Manager',
    '2023-12-17 13:15:00+00',
    '2023-12-17 13:00:00+00',
    5,
    30
),

-- Low Severity Incidents
(
    'INC-2024-031',
    'Password Policy Violations',
    'Multiple users detected using weak passwords that do not meet corporate policy requirements. Password strength analysis revealed common patterns and dictionary words. Enhanced password policy enforcement implemented.',
    'Policy Violation',
    'Low',
    'Resolved',
    'Password Admin - Eric Thompson',
    'Identity Security Analyst',
    '2023-12-16 10:30:00+00',
    '2023-12-16 10:15:00+00',
    1,
    31
),
(
    'INC-2024-032',
    'Printer Security Configuration',
    'Network printers discovered with default administrative credentials and unsecured network protocols. Potential information disclosure risk through print job interception. Security hardening applied to all devices.',
    'Device Security',
    'Low',
    'Closed',
    'Printer Admin - Melissa Garcia',
    'Network Device Manager',
    '2023-12-15 14:45:00+00',
    '2023-12-15 14:30:00+00',
    2,
    32
),
(
    'INC-2024-033',
    'Software License Compliance',
    'Audit revealed unlicensed software installations on multiple workstations. Software includes productivity applications and development tools. License procurement and software removal in progress to ensure compliance.',
    'Compliance Violation',
    'Low',
    'In Progress',
    'License Admin - Jonathan Lee',
    'Software Asset Manager',
    '2023-12-14 12:20:00+00',
    '2023-12-14 12:05:00+00',
    3,
    33
),
(
    'INC-2024-034',
    'Guest Network Misuse',
    'Guest wireless network being used for inappropriate content access and excessive bandwidth consumption. Network monitoring shows streaming and gaming activity. Usage policies updated and bandwidth limits implemented.',
    'Network Misuse',
    'Low',
    'Resolved',
    'Guest Network Admin - Kimberly Martinez',
    'Network Operations Analyst',
    '2023-12-13 15:10:00+00',
    '2023-12-13 14:55:00+00',
    4,
    34
),
(
    'INC-2024-035',
    'Email Signature Compliance',
    'Corporate email signatures missing required legal disclaimers and contact information. Non-compliance with corporate branding and legal requirements identified during audit. Template updates and user training initiated.',
    'Compliance Issue',
    'Low',
    'Open',
    'Email Compliance - Robert Johnson',
    'Communications Manager',
    '2023-12-12 11:40:00+00',
    '2023-12-12 11:25:00+00',
    5,
    35
),
(
    'INC-2024-036',
    'Desktop Wallpaper Policy',
    'Inappropriate desktop wallpapers detected on corporate workstations including personal photos and non-business content. Group policy updated to enforce corporate wallpaper standards and user notification sent.',
    'Policy Violation',
    'Low',
    'Closed',
    'Desktop Policy Admin - Lisa Wilson',
    'Desktop Management Lead',
    '2023-12-11 09:15:00+00',
    '2023-12-11 09:00:00+00',
    1,
    36
),
(
    'INC-2024-037',
    'Time Synchronization Issues',
    'Multiple systems showing time drift beyond acceptable thresholds. Time synchronization critical for log correlation and certificate validation. NTP configuration updated and monitoring enhanced.',
    'System Configuration',
    'Low',
    'Resolved',
    'Time Admin - Charles Davis',
    'Systems Administrator',
    '2023-12-10 16:30:00+00',
    '2023-12-10 16:15:00+00',
    2,
    37
),
(
    'INC-2024-038',
    'Browser Extension Violations',
    'Unauthorized browser extensions detected on corporate workstations including ad blockers and social media tools. Extensions pose potential security risk and violate corporate policy. Removal and policy enforcement initiated.',
    'Policy Violation',
    'Low',
    'In Progress',
    'Browser Admin - Angela Rodriguez',
    'Web Security Analyst',
    '2023-12-09 13:50:00+00',
    '2023-12-09 13:35:00+00',
    3,
    38
),
(
    'INC-2024-039',
    'Screen Saver Policy Compliance',
    'Workstations discovered without mandatory password-protected screen savers. Policy requires automatic lock after 10 minutes of inactivity. Group policy updated and compliance monitoring implemented.',
    'Policy Violation',
    'Low',
    'Resolved',
    'Screen Policy Admin - Kevin Thompson',
    'Desktop Security Specialist',
    '2023-12-08 10:25:00+00',
    '2023-12-08 10:10:00+00',
    4,
    39
),
(
    'INC-2024-040',
    'Inventory Management Discrepancies',
    'IT asset inventory showing discrepancies between physical assets and database records. Missing equipment and untracked devices identified during quarterly audit. Inventory reconciliation and tracking improvements initiated.',
    'Asset Management',
    'Low',
    'Open',
    'Asset Admin - Maria Garcia',
    'Asset Management Coordinator',
    '2023-12-07 14:15:00+00',
    '2023-12-07 14:00:00+00',
    5,
    40
),
(
    'INC-2024-041',
    'Conference Room Technology Issues',
    'Video conferencing equipment in multiple conference rooms showing security vulnerabilities including default passwords and outdated firmware. Equipment hardening and update schedule implemented.',
    'Device Security',
    'Low',
    'In Progress',
    'AV Admin - Steven Martinez',
    'Facilities Technology Manager',
    '2023-12-06 12:45:00+00',
    '2023-12-06 12:30:00+00',
    1,
    41
),
(
    'INC-2024-042',
    'Parking Lot WiFi Interference',
    'External WiFi networks detected in parking area with similar names to corporate network. Potential evil twin attack setup. Physical security notified and network monitoring enhanced. Warning communications sent to staff.',
    'Physical Security',
    'Low',
    'Closed',
    'Physical Security - Diana Johnson',
    'Security Operations Center',
    '2023-12-05 17:20:00+00',
    '2023-12-05 17:05:00+00',
    2,
    42
),
(
    'INC-2024-043',
    'Vendor Badge Access Review',
    'Quarterly review revealed vendor access badges not returned after contract completion. 12 badges remain active for terminated vendor relationships. Badge deactivation and access review procedures updated.',
    'Access Management',
    'Low',
    'Resolved',
    'Badge Admin - Paul Wilson',
    'Physical Access Manager',
    '2023-12-04 11:30:00+00',
    '2023-12-04 11:15:00+00',
    3,
    43
),
(
    'INC-2024-044',
    'Cafeteria POS System Update',
    'Point-of-sale systems in employee cafeteria running outdated software with known vulnerabilities. Systems process employee payment cards and personal information. Security patches and monitoring implemented.',
    'System Vulnerability',
    'Low',
    'Open',
    'POS Admin - Jennifer Davis',
    'Retail Systems Manager',
    '2023-12-03 15:45:00+00',
    '2023-12-03 15:30:00+00',
    4,
    44
),
(
    'INC-2024-045',
    'Emergency Contact Information',
    'Employee emergency contact information audit revealed outdated and missing contact details for 25% of staff. Information critical for incident response and business continuity. Data collection campaign initiated.',
    'Data Quality',
    'Low',
    'In Progress',
    'HR Data Admin - Michelle Thompson',
    'Human Resources Manager',
    '2023-12-02 09:20:00+00',
    '2023-12-02 09:05:00+00',
    5,
    45
),
(
    'INC-2024-046',
    'Elevator Security Camera Malfunction',
    'Security cameras in building elevators experiencing intermittent failures. Physical security monitoring gaps identified during routine inspection. Camera replacement and backup monitoring procedures implemented.',
    'Physical Security',
    'Low',
    'Resolved',
    'Camera Admin - Richard Garcia',
    'Building Security Manager',
    '2023-12-01 13:10:00+00',
    '2023-12-01 12:55:00+00',
    1,
    46
),
(
    'INC-2024-047',
    'Recycling Bin Data Security',
    'Sensitive documents discovered in general recycling bins without proper shredding. Documents contained employee information and business plans. Secure disposal procedures reinforced and additional shredding stations installed.',
    'Data Protection',
    'Low',
    'Closed',
    'Facilities Admin - Sandra Martinez',
    'Facilities Security Coordinator',
    '2023-11-30 16:40:00+00',
    '2023-11-30 16:25:00+00',
    2,
    47
),
(
    'INC-2024-048',
    'Loading Dock Security Gap',
    'Loading dock area identified with security camera blind spots and inadequate lighting. Potential unauthorized access point during delivery hours. Lighting upgrades and additional camera coverage implemented.',
    'Physical Security',
    'Low',
    'Open',
    'Dock Security - William Johnson',
    'Facilities Security Manager',
    '2023-11-29 14:30:00+00',
    '2023-11-29 14:15:00+00',
    3,
    48
),
(
    'INC-2024-049',
    'Visitor Management System Glitch',
    'Electronic visitor management system experiencing database synchronization issues. Visitor badges occasionally not deactivating after checkout. Manual verification procedures implemented while system undergoes maintenance.',
    'System Malfunction',
    'Low',
    'In Progress',
    'Visitor System Admin - Carol Wilson',
    'Reception Security Manager',
    '2023-11-28 10:50:00+00',
    '2023-11-28 10:35:00+00',
    4,
    49
),
(
    'INC-2024-050',
    'Company Vehicle GPS Tracking',
    'GPS tracking systems in company vehicles showing location accuracy issues and delayed reporting. Fleet security and emergency response capabilities affected. System calibration and backup tracking methods implemented.',
    'Vehicle Security',
    'Low',
    'Resolved',
    'Fleet Admin - Donald Davis',
    'Fleet Security Manager',
    '2023-11-27 12:15:00+00',
    '2023-11-27 12:00:00+00',
    5,
    50
);

-- Update the updated_at timestamp for all records
UPDATE incidents SET updated_at = NOW();

-- Create additional indexes for better performance
CREATE INDEX IF NOT EXISTS idx_incidents_incident_type ON incidents(incident_type);
CREATE INDEX IF NOT EXISTS idx_incidents_reported_by ON incidents(reported_by);
CREATE INDEX IF NOT EXISTS idx_incidents_assigned_to ON incidents(assigned_to);

-- Add some comments for documentation
COMMENT ON TABLE incidents IS 'Comprehensive incident tracking with 50 sample records covering various security incident types';
COMMENT ON COLUMN incidents.incident_id IS 'Unique incident identifier following INC-YYYY-NNN format';
COMMENT ON COLUMN incidents.severity IS 'Incident severity: Critical, High, Medium, Low';
COMMENT ON COLUMN incidents.status IS 'Current incident status: Open, In Progress, Resolved, Closed';
